### ISSUE TITLE
'Cordova/CDVUserAgentUtil.h' file not found on cordova-ios@6

### ISSUE THREAD

**Issue by nagaperla** [apache/cordova-plugin-inappbrowser#818] opened 2020-11-17 13:06 UTC
# Bug Report
Recently, I updated my cordova app from cordova-ios@5.1.1 to @6.1.1 using the following steps -
`cordova platform remove ios`
`cordova platform add ios@6.1.1`

After adding a new platform work, I tried to build ios using `cordova build ios`. Then I got this fatal error issue -
## Problem
**Plugins/cordova-plugin-inappbrowser/CDVWKInAppBrowser.m:27:9: fatal error: 'Cordova/CDVUserAgentUtil.h' file not found
#import <Cordova/CDVUserAgentUtil.h>
1 error generated.**

### What is expected to happen?
Should build successfully. 

### What does actually happen?
Not sure why this actually happening.

## Information

Further, I tried to re-install ios@6 after remove all plugins, ios@5 platform. Still didn't solve my problem. 

### Command or Code

Would be great, if anyone suggests ideas to solve the problem. Thanks in advance

### Version information

Cordova: 10.0.0
Xcode: 12.2 (Build version: 12B45b)
cordova-ios: 6.1.1
Operating system: macOS
cordova-plugin-inappbrowser: Latest version (Pulling from github repo source)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment] 2020-11-17 14:36
You need to use v4.0.0 of the corodova-plugin-inappbrowser. You might as well have a dirty platforms folder, you can try to remove the whole `platforms/ios` folder and re-add it with `cordova platform add ios`. Duplicate of #709 and #712.

**Closed by timbru31** 2020-11-17 14:36 UTC

**Comment by nagaperla** [comment] 2020-11-20 14:14
@timbru31 Thank you for responding. I tried the approach you've mentioned. Still, the issue isn't resolved completely. Here is the list of Cordova plugins I'm using in my app -
branch-cordova-sdk 3.4.0 "branch-cordova-sdk"
cordova-ios-plugin-no-export-compliance 0.0.5 "iOS No Export Compliance"
cordova-plugin-fastclick 1.0.0 "FastClick"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-plugin-wkwebviewxhrfix 0.1.0 "WKWebView XHR Fix"
pushwoosh-cordova-plugin 8.0.0 "Pushwoosh"

There are other issues that are coming up with v4.0.0. List of errors:
Plugins/cordova-plugin-wkwebview-engine/CDVWKWebViewEngine.m:104:80: error: property 'userAgent' not found on object of type 'CDVViewController *'
        wkWebView.customUserAgent = ((CDVViewController*) self.viewController).userAgent;
                                                                               
Plugins/cordova-plugin-wkwebview-engine/CDVWKWebViewEngine.m:375:6: error: use of undeclared identifier 'CDVUserAgentUtil'
    [CDVUserAgentUtil releaseLock:vc.userAgentLockToken];
     ^
Plugins/cordova-plugin-wkwebview-engine/CDVWKWebViewEngine.m:388:6: error: use of undeclared identifier

**Comment by erisu** [comment] 2020-11-20 14:39
Remove the plugin `cordova-plugin-wkwebview-engine`. This plugin should not be installed with Cordova-iOS 6.x. Cordova-iOS 6.x does not support this plugin.

Also if you read the new error message, you can see it is coming from `cordova-plugin-wkwebview-engine`, not IAB anymore.

The original error message you posted `Plugins/cordova-plugin-inappbrowser/CDVWKInAppBrowser.m: ` was because you were using an old IAB plugin which was not supported by Cordova-iOS 6.x.

Now your issue is the `cordova-plugin-wkwebview-engine`.

**Comment by nagaperla** [comment] 2020-11-20 16:19
Thanks @erisu for your help. It solved the issue.

**Comment by Finedl** [comment] 2020-12-06 14:31
> Remove the plugin `cordova-plugin-wkwebview-engine`. This plugin should not be installed with Cordova-iOS 6.x. Cordova-iOS 6.x does not support this plugin.
> 
> Also if you read the new error message, you can see it is coming from `cordova-plugin-wkwebview-engine`, not IAB anymore.
> 
> The original error message you posted `Plugins/cordova-plugin-inappbrowser/CDVWKInAppBrowser.m: ` was because you were using an old IAB plugin which was not supported by Cordova-iOS 6.x.
> 
> Now your issue is the `cordova-plugin-wkwebview-engine`.

‘cordova-plugin-wkwebview-engine’ is not present in the project......what should I do? sir
