### ISSUE TITLE
Enable camera access via the input file.

### ISSUE THREAD

**Issue by hostcia** [apache/cordova-plugin-inappbrowser#772] opened 2020-09-03 16:30 UTC
I'm using InAppBrowser, to open an external form.

In this form there is an input file, so that the person can take a photo and attach it to the form.

When I access the link through the browser, the access of the cell phone camera works correctly, but when I access it via InAppBrowser or an iframe, the input file does not open the camera.

Is it necessary to enable some resource in the cord so that the camera can be accessed via InAppBrowser or iframe?

```
<script>
        document.addEventListener("deviceready", onDeviceReady, false);
        function onDeviceReady() {
            cordova.InAppBrowser.open('https://apps.url.com/index.php', '_blank', 'location=no');

            navigator.mediaDevices.getUserMedia({
                'audio': true,
                'video': {
                    facingMode: 'environment'
                }
            })
        }
    </script>
```

Plugins being used:

```
"cordova-plugin-camera": "^4.1.0",
"cordova-plugin-file": "^6.0.2",
"cordova-plugin-media-capture": "^3.0.3",
"cordova-plugin-whitelist": "^1.3.4"
```

**Comment by mattsputnikdigital** [comment] 2020-09-10 09:23
Is this Android, as in iOS it works for me.

But in Android I could never get it to work with the Camera, so for Android I use cordova-plugin-safariviewcontroller which uses a different type of webview in Android and the camera works. I still use InAppBrowser for iOS.

**Comment by ljudbane** [comment] 2020-09-16 10:32
Might be related to the camera permissions. Check this issue: https://github.com/apache/cordova-plugin-inappbrowser/issues/706.

I've used the solution described in that issue to access camera on web age in InAppBrowser.

**Comment by jcesarmobile** [comment] 2020-10-01 13:33
duplicate of https://github.com/apache/cordova-plugin-inappbrowser/issues/328

**Closed by jcesarmobile** 2020-10-01 13:33 UTC
