### ISSUE TITLE
Solving issue #417 generated a new issue for inappbrowser when using usewkwebview=yes

### ISSUE THREAD

**Issue by mosababubakr** [apache/cordova-plugin-inappbrowser#424] opened 2019-02-11 16:20 UTC
@janpio @dpa99c @agrieve @stevengill @shazron @purplecabbage @timbru31 @sgrebnov
(After the old issue https://github.com/apache/cordova-plugin-inappbrowser/issues/417 solved , there is a new issue appear in inappbrowser load errors if you open any websites. and warning messages appear from header).
When @janpio @dpa99c edited the code to resolve #417 issue, there a new issue generated.

Please check inappbrowser plugin master version and try to open any website inside inappbrowser using usewkwebview=yes, and you will see that you can't see the websites.

You can try to open: https://www.trivago.com/ in inappbrowser as an example.

Before solving issue #417 , this new issue not appear, it is just appear after issue #417 solved.

Please check

Thanks.
Regards.

**Comment by mosababubakr** [comment] 2019-02-11 20:08
@janpio @dpa99c please check the previous updated code, now: you can't open any websites, HEADER BROWSER HAVE AN ERROR

**Comment by dpa99c** [comment] 2019-02-11 21:40
OK, I see the problem here. My fix for #417 is screwing up sites using iframes (such as Trivago) because it's also redirecting those cross-frame requests back to the main IAB frame.
What it needs to do is only redirect the request back to the main frame if the target attribute is "_blank".
That should handle both cases.

**Comment by mosababubakr** [comment] 2019-02-11 22:04
Hello @dpa99c 
Thanks for reply,
When you will fix the issue for the master version ?

Regards

**Comment by dpa99c** [comment] 2019-02-11 22:10
@mosababubakr I have created PR #425 which should resolve this issue and also preserve the fix for #417.

Please could you test the changes on my branch and confirm they resolve all your issues before this PR is merged to master. 

To install the plugin direct from my branch, you can use:

    cordova plugin add https://github.com/dpa99c/cordova-plugin-themeablebrowser#GH-242-fix-ios-wkwebview-iframes

@janpio would be good to have some wider testing of this before it gets merged to confirm no other regression bugs have been introduced.

**Comment by mosababubakr** [comment] 2019-02-11 22:29
Hello @dpa99c 
Thanks for help,
I try to use the plugin you mentioned and every things work fine now.

Thanks

Just now we wait for the master version to merge and fix these issue.


Regards

**Closed** 2019-02-11 23:14 UTC
