### ISSUE TITLE
Impossible to build ionic app

### ISSUE THREAD

**Issue by ghost** [apache/cordova-plugin-inappbrowser#416] opened 2019-02-07 07:44 UTC
I try to build my ionic app for android and the build crashed.

`[cordova]  C:\Users\fr\Documents\Projects\Horus Smart\platforms\android\app\src\main\java\org\apache\cordova\inappbrowser\InAppBrowser.java:60: error: cannot find symbol
[cordova]  import org.apache.cordova.ApiConfig;
[cordova]                           ^
[cordova]    symbol:   class ApiConfig
[cordova]    location: package org.apache.cordova
[cordova]  C:\Users\fr\Documents\Projects\Horus Smart\platforms\android\app\src\main\java\org\apache\cordova\inappbrowser\InAppBrowser.java:177: error: cannot find symbol
[cordova]                                  Method iuw = ApiConfig.class.getMethod("isUrlWhiteListed", String.class);
[cordova]                                               ^
[cordova]    symbol: class ApiConfig
`

Thanks in advance,

François

**Comment by webprofusion-chrisc** [comment] 2019-02-11 01:53
Try:
- remove and add the inappbrowser again, ensure you have the latest version
- `cordova clean`

**Comment by jcesarmobile** [comment] 2020-04-11 14:26
closing as the reporter account was deleted and I can't reproduce that error

**Closed by jcesarmobile** 2020-04-11 14:26 UTC
