### ISSUE TITLE
Unable to access Camera and Microphone functionalities in InAppBrowser

### ISSUE THREAD

**Issue by yaminikonduru** [apache/cordova-plugin-inappbrowser#741] opened 2020-06-24 13:53 UTC
# Bug Report
# Unable to access Camera and Microphone, even if application has permission to access both functionalities.

### Happening 
 Working on cordova Android Application(using Angularjs), In application user need access of camera and microphone to click photo/ record video/record response, i have added cordova plugins(cordova-plugin-inappbrowser-camera,cordova-plugin-media-capture) for accessing camera and recording video and enabled permissions too, but while checking permissions using `navigator.mediaDevices.getUserMedia()` it throws permission denied. It is expected to access camera and microphone, after granting the permissions in the application,else it has to prompt a dialog box for requesting permissions.

### Expected
when we open same link in browser, browser prompts for requesting the permission to access camera and microphone, user can grant permission or user can deny, requesting dialog box also doesn't appear in inAppBrowser.

### Command or Code

Added plugins using 
```
cordova plugin add cordova-plugin-inappbrowser
cordova plugin add cordova-plugin-camera
cordova plugin add cordova-plugin-media-capture
```

Invoking inAppBrowser using this code:

```
    var url ="https://webrtc.github.io/samples/src/content/devices/input-output/",
             target = "_blank",
             options = "location=no";

    inAppBrowserRef = cordova.InAppBrowser.open(url, target, options);
```
Tried fetching device information using 
```
 navigator.mediaDevices.getUserMedia({
      'audio': true,
      'video': {
          facingMode: 'environment'
      }
  })
```
Fetching device information on browser using *navigator.mediaDevices.getUserMedia* works as expected, but not able to work on android device

### Environment, Platform, Device
In all Android devices( targeting 4.4 - 9.0.0)

### Version information

  ```
    Node version:  tried both v6.10.3 and v14.2.0, 
    NPM version:  v3.10.10,
   "cordova-android": "^8.1.0",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-inappbrowser": "^4.0.0",
    "cordova-plugin-media-capture": "^3.0.3"
```

## Checklist

- [x] I searched for existing GitHub issues, [https://github.com/apache/cordova-plugin-inappbrowser/issues/706]( found similar one involving Ionic)
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by joeljfernandes** [comment] 2020-06-30 15:48
I am experiencing this same issue...please help me!

**Comment by timbru31** [comment] 2020-06-30 15:52
Closing as a duplicate of #706

**Closed by timbru31** 2020-06-30 15:52 UTC
