### ISSUE TITLE
in _blank mode the microfon not work

### ISSUE THREAD

**Issue by tib256** [apache/cordova-plugin-inappbrowser#974] opened 2022-09-05 08:12 UTC
# Feature Request
If I start the inappbrowser the microfon not work in Android. I/chromium: [INFO:CONSOLE(48)] "Uncaught (in promise) NotAllowedError: Permission denied", 
I would like ask , I can use microfone in _blank mode too. I can use microfon in _self mode, but I have another problems.

**Comment by hussain-github** [comment] 2022-09-17 09:49
Any updates on this?

**Comment by tib256** [comment] 2022-09-17 18:01
We don't use download links in _self mode, never mind we found another solution.

**Comment by hussain-github** [comment] 2022-09-17 20:33
> I don't use download links in _self mode, never mind. I found another solution.

Kindly share your solution for getting microphone to work.

**Comment by jcesarmobile** [comment] 2022-09-25 03:48
Closing as duplicate of https://github.com/apache/cordova-plugin-inappbrowser/issues/969

**Closed by jcesarmobile** 2022-09-25 03:48 UTC
