### ISSUE TITLE
Android build fails because of EOL conversion in png files

### ISSUE THREAD

**Issue by BrandOuellette** [apache/cordova-plugin-inappbrowser#497] opened 2019-06-28 18:04 UTC
Android build fails since last commit (June 27, 2019).

I believe it is because of EOL conversion caused the png files, and made them invalid.

Our android builds worked perfectly until yesterday's commit, now it fails saying they are invalid PNG files.

**Comment by janpio** [comment] 2019-06-28 20:24
Ok, I was wondering what was going on in https://github.com/apache/cordova-plugin-inappbrowser/commit/e44ad9192a039ca6ea0afe08b827e98e2edfad44 but couldn't figure it out at the time.

Are you including inappbrowser from `master` here in your project?
Can you post the error output you are getting?

**Comment by janpio** [comment] 2019-06-28 20:39
Tried to reproduce the problem, but couldn't:

````E:\Projects\throwaway
λ cordova create cordovaIABReleaseTest2
Creating a new cordova project.

E:\Projects\throwaway
λ d cordovaIABReleaseTest2
'd' is not recognized as an internal or external command,
operable program or batch file.

E:\Projects\throwaway
λ cd cordovaIABReleaseTest2

E:\Projects\throwaway\cordovaIABReleaseTest2  (helloworld@1.0.0)
λ cordova platform add android
Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: io.cordova.hellocordova
        Name: HelloCordova
        Activity: MainActivity
        Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.0.0
Plugin 'cordova-plugin-whitelist' found in config.xml... Migrating it to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Adding cordova-plugin-whitelist to package.json

E:\Projects\throwaway\cordovaIABReleaseTest2  (helloworld@1.0.0)
λ cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser#3.1.0
Installing "cordova-plugin-inappbrowser" for android
Adding cordova-plugin-inappbrowser to package.json

E:\Projects\throwaway\cordovaIABReleaseTest2  (helloworld@1.0.0)
λ cordova plugin list
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-whitelist 1.3.3 "Whitelist"

E:\Projects\throwaway\cordovaIABReleaseTest2  (helloworld@1.0.0)
λ cordova build android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\Jan\AppData\Local\Android\sdk (DEPRECATED)
Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 1m 19s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest
...
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug
> Task :app:transformDexArchiveWithDexMergerForDebug
> Task :app:mergeDebugJniLibFolders
> Task :CordovaLib:compileDebugNdk NO-SOURCE
> Task :CordovaLib:mergeDebugJniLibFolders
> Task :CordovaLib:transformNativeLibsWithMergeJniLibsForDebug
> Task :CordovaLib:transformNativeLibsWithIntermediateJniLibsForDebug
> Task :app:transformNativeLibsWithMergeJniLibsForDebug
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug
> Task :app:packageDebug
> Task :app:assembleDebug
> Task :app:cdvBuildDebug

BUILD SUCCESSFUL in 4m 8s
42 actionable tasks: 42 executed
Built the following apk(s):
        E:\Projects\throwaway\cordovaIABReleaseTest2\platforms\android\app\build\outputs\apk\debug\app-debug.apk
```

```
λ cordova info
cordova-lib@9.0.1 with:
  cordova-common@3.1.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment:
  OS: win32
  Node: v12.3.1
  npm: 6.9.0
```

Can you post the exact commands to reproduce? And best the start of your `cordova info` output please?

**Comment by BrandOuellette** [comment] 2019-06-28 20:57
We use the latest version of Phonegap Build, which is where the error occurred. iOS built successfully, Android failed. If you change the Git EOL conversion to ignore PNG files it would probably fix this issue. I'll post the log tomorrow.

**Comment by BrandOuellette** [comment] 2019-06-28 21:05
If you look at the PNG files on GitHub.Com, you can see they're broken.

**Comment by janpio** [comment] 2019-06-28 21:18
Ok, `master` should be fixed.

Still would be interested what your setup is so that you get the unreleased `master` of this plugin in your project, a look at your `config.xml` and `package.json` would be interesting. 

Also the build log, because both CI and my local system did not complain about these images, which is a bit strange and unsettling. I want to be able to trust our tests and CI :/

**Comment by BrandOuellette** [comment] 2019-06-28 21:26
No problem, I'll post it all tomorrow. We used to use the latest npm version but switched to the latest git master for this plugin mainly so we could use the WKWebView on iOS since there was a bug in the old one we couldn't work around.

-------- Original message --------

**Comment by janpio** [comment] 2019-06-28 21:55
Ok - then the upcoming release is probably a good time to switch back. Will be live in a few days on npm.

(Closing this now so nobody else gets confused, but I am looking forward to looking at the details tomorrow or next week.)

**Comment by janpio** [comment] 2019-06-28 21:56
By the way: https://github.com/apache/cordova/issues/134 👍

**Closed by janpio** 2019-06-28 21:55 UTC
Labels: bug

**Comment by BrandOuellette** [comment] 2019-06-29 11:55
The Good News: Android now builds successfully.
The Bad News: We now can't show you the build log with the error because I can't find any documentation on how to specify a specific git commit id for a plugin in the config.xml file.

Nonetheless, in case it helps, I've attached our last config.xml file and build log for the Android build that just ran successfully. You can use it to reproduce the error if you know how to change specify a specific git commit id for this plugin, and you use build.phonegap.com to build it for android.

Phonegap Version: cli-8.1.1
Android: 7.1.2

[build.log](https://github.com/apache/cordova-plugin-inappbrowser/files/3341820/build.log)

[config.xml.txt](https://github.com/apache/cordova-plugin-inappbrowser/files/3341823/config.xml.txt)

In regards to the CI not catching it, keep in mind that when we built for iOS, it built successfully even though the PNG files were corrupt. So if you really want the CI to catch this type of thing, you would have to have it check every image file to make sure they are valid given the extension (i.e. a file ending in ".png" is a valid PNG image).

**Comment by janpio** [comment] 2019-06-29 12:37
> The Bad News: We now can't show you the build log with the error because I can't find any documentation on how to specify a specific git commit id for a plugin in the config.xml file.

Worse news: As I was reckless, and force pushed the cleaned up `master`, that commit is gone anyway 🤷‍♀ You can't access the old build logs somehow?

> In regards to the CI not catching it, keep in mind that when we built for iOS, it built successfully even though the PNG files were corrupt. So if you really want the CI to catch this type of thing, you would have to have it check every image file to make sure they are valid given the extension (i.e. a file ending in ".png" is a valid PNG image).

What I meant here was that every change in a plugin is built by our CI, so anything being broken should have been caught there. 
But of course we don't use Phonegap Build but a local build on Travis, so maybe they got tripped up somehow.

**Comment by BrandOuellette** [comment] 2019-06-29 13:50
Unfortunately, Phonegap Build doesn't keep a history of build logs. However, we do have the specific error messages from the log when the build failed.

The fatal error message was...
Execution failed for task ':app:mergeReleaseResources'.

And there were a lot of..
... error: failed to read PNG signature: file does not start with PNG signature.
for the PNG files in the plugin.

As for Travis CI. I've never heard of a local Travis CI, but if it didn't pull from GIT after the EOL conversion and ran from your local environment, you wouldn't have the bug in the build since the PNG files weren't changed by git and remained valid.

For our CI process, we check any images that have changed as part of a manual QA process before we push out a public release since a computer can't tell if an image is valid visually in a certain context, so we don't bother checking the binary validity of the files.

**Comment by janpio** [comment] 2019-06-29 14:06
> As for Travis CI. I've never heard of a local Travis CI, but if it didn't pull from GIT after the EOL conversion and ran from your local environment, you wouldn't have the bug in the build since the PNG files weren't changed by git and remained valid.

"local Travis" vs. "remote PhonegapBuild" in this case. We run also tests on a "remote SauceLabs device" for the plugins, hence that naming. But I meant a normal Travis CI build that checks out the repo for every build, so this should have cause problems there as well.

> For our CI process, we check any images that have changed as part of a manual QA process before we push out a public release since a computer can't tell if an image is valid visually in a certain context, so we don't bother checking the binary validity of the files.

In theory I do as well, in practice I did releases for 16 Cordova Core plugins in the last few days with a few hundred commits, so this slipped through as I finally wanted to get these out as well. It has been stressful 🤷‍♀

**Comment by janpio** [comment] 2019-06-29 14:07
Oh, the commit still seems to be there after all. You could use `cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser#e44ad9192a039ca6ea0afe08b827e98e2edfad44` to install the plugin from that state.

**Comment by BrandOuellette** [comment] 2019-06-29 16:31
Well your work is extremely appreciated, I don't know what we'd do if we had to develop any of the core plugins ourselves. I imagine bankruptcy. 😉

I can't use "cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser#e44ad9192a039ca6ea0afe08b827e98e2edfad44" because we don't use the Cordova CLI.  I'm not sure it will work with Phonegap Build if I use that URL in config.xml because from what I gather, Git URLs have to end in ".git" like in the config.xml I posted. I can try it though if you think it will pick up and use that commit.

It's very strange that Travis didn't have the same error as with Phonegap Build. I did read somewhere that it checks image resources more strictly when building in production mode, which we were.

**Comment by janpio** [comment] 2019-06-29 16:54
Hm, I don't know enough about the Phonegap CLI to give you advice here, sorry. But not that important now that it is fixed - was my mistake after all.

**Comment by BrandOuellette** [comment] 2019-06-29 17:39
Phonegap CLI is built on top of the Cordova CLI so it's probably the same command but we don't use either.

It doesn't matter who's mistake it was as long as it's fixed. 😀 Doing something is always better than nothing. That being said, I think it was Git's mistake for converting the EOL for binary files as a default.

**Comment by janpio** [comment] 2019-06-29 18:58
That is something I don't understand as well... from me reading the docs I got the impression that this used to be necessary, but now shouldn't any more. Hence I just committed the files :/

**Comment by BrandOuellette** [comment] 2019-06-30 11:40
Maybe Phonegap Build is using an old version of git, who knows.

This probably isn't the right place to ask but I don't know where else to... Do you know if it's possible to just change/customize the User Agent the inappbrowser uses? I know you can change it in config.xml for the entire Cordova app, but we just want the requests sent in the inappbrowser to be a custom user agent string.

**Comment by janpio** [comment] 2019-07-01 08:39
I don't think that is possible (yet). My apps usually only load local files (or APIs) in the main webview, so I never encountered that need.

Feel free to open a feature request, maybe this isn't that hard to implement.
