### ISSUE TITLE
InApp browser not support in iPhone X devices

### ISSUE THREAD

**Issue by ersatishverma** [apache/cordova-plugin-inappbrowser#306] opened 2018-09-26 12:58 UTC
Hi 
Currently, i am using latest inappbrowser plugin 3.0.0
node v8.11.1
npm v5.6.0
PhoneGap cli-8.0.0

Facing some issues in iPhone X device.
**Current behavior:** 

1. inappbrowser distorted UI in the status bar section.
2. In the bottom bar URL load section shown in the safe area.
3. website load under the toolbar section.

**Expected behavior**

1. toolbar covers the status bar section also like other apps.
2. Bottom load URL show above the safe area.
3. Load website starts after the toolbar section.

Option Fileds that I am using.
Code :
`hidden=yes,mediaPlaybackRequiresUserAction=yes,closebuttoncaption=Done,toolbarposition=top,enableViewportScale=yes,toolbar=yes,toolbarcolor=#8bc34a,hidenavigationbuttons=no,navigationbuttoncolor=#ffffff,closebuttoncolor=#8bc34a`

![image](https://user-images.githubusercontent.com/39588047/46081344-ec28af80-c1b9-11e8-88ea-f14ec12e89eb.png)

Thanks In Advance :pray::skin-tone-2:

**Comment by vagishmm** [comment] 2018-09-26 14:51
1) For this issue add iPhone X splash images in Images.xcassets. Automatically it will fix your UI issue.
Please use below sizes for iPhone X

**Device               | Portrait size          | Landscape size**
iPhone XS Max | 1242px × 2688px | 2688px × 1242px
iPhone XS         | 1125px × 2436px | 2436px × 1125px
iPhone XR         | 828px × 1792px   | 1792px × 828px
iPhone X           | 1125px × 2436px | 2436px × 1125px


2)For Bottom URL please use this options.
location=no,toolbar=no,hardwareback=no

**Comment by ersatishverma** [comment] 2018-10-05 05:18
Hi **vagishmm**
Thanks for reply 

Have made changes that you have suggested.
The bottom URL problem resolved, many thanks.
But the status bar problem remains the same.
![image](https://user-images.githubusercontent.com/39588047/46517264-16e6c800-c88c-11e8-9ab8-924babdb26e9.png)

**Comment by vespino** [comment] 2018-10-22 06:03
@ersatishverma were you able fix this issue? Using the other splash images doesn't help, because those are not yet supported by Phonegap.

**Comment by vespino** [comment] 2018-10-22 07:46
@vagishmm were you able to solve this issue? Adding the splashscreens does not solve it and iPhone X has been around for over a year now, so you would think the guys at Phonegap would have fixed this by now.

**Comment by ersatishverma** [comment] 2018-10-22 10:51
Hi @vespino
yes, these splash images doesn't help me too. 
and my issue remains the same is not fix yet.

**Comment by dmonaldo** [comment] 2018-11-16 20:21
I'm also experiencing this issue. Are there any plans to fix this?

**Comment by ersatishverma** [comment] 2019-02-02 05:41
Hi @noahcooper 
Yes, manually edit Objective-C files not a good solution.

I switched to another plugin for ios devices 
https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller
and it's working for me.

**Comment by alexyazvinsky** [comment] 2019-03-11 20:54
Any update?

**Comment by Sagarkhenat** [comment] 2019-04-01 09:04
I am also facing this issue,will the cordova plugin team look into this,the InApp browser is not functioning correctly for iPhoneX probablye because of it's notch design.

**Comment by ersatishverma** [comment] 2019-04-01 14:35
@Sagarkhenat 
I switched to another plugin for ios devices you can use this one its support all iPhone notch designs.
https://github.com/EddyVerbruggen/cordova-plugin-safariviewcontroller

**Comment by noahcooper** [comment] 2019-04-02 13:32
+1 for cordova-plugin-safariviewcontroller. It is a much better experience on iOS.

**Comment by de-dan** [comment] 2019-04-02 20:18
The safariviewcontroller might be the better choice for the average user, but unfortunately not in my case: the app is running/wrapped in a Citrix XenMobile environment, which currently supports only the UIWebView engine.

**Comment by clerkzhang** [comment] 2019-04-03 11:58
Any update?

**Comment by thanveershah** [comment] 2019-06-04 10:44
Any Update?

**Comment by vadimwe** [comment] 2020-03-05 16:27
+++++

**Comment by NiklasMerz** [comment] 2020-03-06 07:23
Please check this issue about the removal of the "fake" statusbar #604

**Comment by jcesarmobile** [comment] 2020-04-11 14:17
closing as duplicate of https://github.com/apache/cordova-plugin-inappbrowser/issues/301

**Closed by jcesarmobile** 2020-04-11 14:17 UTC
Labels: platform: ios, support
