### ISSUE TITLE
iphone 10 notch issue in inappbrowser 

### ISSUE THREAD

**Issue by Baswanth129** [apache/cordova-plugin-inappbrowser#525] opened 2019-08-21 06:04 UTC
# Bug Report

### What is expected to happen?

if the view is loaded in the browser  set status bar height must be set to 46px instead of 20px(which is hard coded in plugin file cdvuiinappbrowser.m)

### What does actually happen?
it is has been set to 20px and displaying a half greyed screen it can be made to zero by changing "statusbar.height to 0 in viewdidload(){}"  in plugin but changing plugin is not coding format 

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by NiklasMerz** [comment] 2019-09-05 09:14
See https://github.com/apache/cordova-plugin-inappbrowser/issues/301#issuecomment-452220131

**Comment by jcesarmobile** [comment] 2020-04-11 14:34
closing as duplicate of https://github.com/apache/cordova-plugin-inappbrowser/issues/301

**Closed by jcesarmobile** 2020-04-11 14:34 UTC
