### ISSUE TITLE
executeScript does not fire - issue ionic 3

### ISSUE THREAD

**Issue by sid-Puttur** [apache/cordova-plugin-inappbrowser#279] opened 2018-08-12 14:12 UTC
I am using this plugin in ionic 3. 
Here is the piece of code

 browser.on('loadstop').subscribe(event => {

        console.log(event,"event inside browser on")
     browser.executeScript({code: 'mycallback'}).then(data=>{
         console.log("script executed",data);
        },err=>{
          console.log(err,"error in executing the script");
        })

    });

loadstop event is working fine, but executeScript doesnot work. Its not going to err section also.

**Comment by janpio** [comment] 2018-08-12 15:54
`browser` is not an object being provided by this plugin. Where does this come from?
Did you ask on the Ionic Forum, Slack or any other support channel?

**Comment by TwashRocketLoans** [comment] 2018-10-04 04:29
pretty sure his browser variable comes from the Ionic docs:

```
import { InAppBrowser } from '@ionic-native/in-app-browser';

constructor(private iab: InAppBrowser) { }


...


const browser = this.iab.create('https://ionicframework.com/');

browser.executeScript(...);

browser.insertCSS(...);
browser.on('loadstop').subscribe(event => {
   browser.insertCSS({ code: "body{color: red;" });
});

browser.close();
```

**Comment by willie001** [comment] 2018-10-05 05:29
This is a real issue.

The InAppBrowser executeScript used to work fine. After compiling my app again the "callback" or "promise" is not executed.

Here is my code that used to work:
`const ref = cordova.InAppBrowser.open(someURL, '_blank', 'location=yes');

ref.addEevntListener('loadstop', () => {
  ref.executeScript({ code: 'someFunctionWithReturnValue();', (data) => {
    if (data[0] != null) {
      alert(JSON.parse(data[0]);
    }
  }
});`

Here is a suggestion that it must be used as a promise but it also does not work:
`ref.executeScript({code: 'getAuthenticationInfo();'}).then((data) => {
  alert(JSON.parse(data[0]));
  }).catch((e) => {
   alert(e);
  });`

I really don't have an answer to this one. Already spend too much time on this issue. As I said, it used to work fine with the callback function but not anymore.

**Comment by willie001** [comment] 2018-10-09 06:42
The issue for me is directly related to #303. The amount of data I returned is too much and is truncated by Chrome. This invalidates the JSON string and the event is never fired.

Hope this helps someone that was struggling with this problem.

**Comment by jcesarmobile** [comment] 2018-12-02 19:59
Closing as duplicate of #303 as it has more information

**Closed by jcesarmobile** 2018-12-02 19:59 UTC
Labels: support
