### ISSUE TITLE
inappbrowser with option usewkwebview=yes does not support iPhone x screen

### ISSUE THREAD

**Issue by mosababubakr** [apache/cordova-plugin-inappbrowser#437] opened 2019-03-02 18:33 UTC
# Bug Report

## Problem
inappbrowser with option usewkwebview=yes does not support iPhone x screen

![untitled-1](https://user-images.githubusercontent.com/47486787/53686419-5d532c80-3d2f-11e9-86d3-49f8383fdd61.jpg)

### What is expected to happen?
Inappbrowser should appear correctly in iphone x devices when the device is in portrait mode or in landscape mode if you set usewkwebview=yes.
(Inappbrowser should work and appear as Safari, with safe margins).

### What does actually happen?
If you try to open an app with inappbrowser using iphone x device using option usewkwebview=yes, then you will notice a problem in the top of screen, because, inappbrowser with usewkwebview=yes not updated to fit iphone x screen device until now.

In portrait mode: Inappbrowser upper side will conflict with status bar and distort the style.
In Landscape mode: the content of the page in the left section will be hidden , and the status bar will be in grey color, status bar in safari landscape not appear.

Inappbrowser option: location=no, usewkwebview=yes 

( Please note that most companies start making their phones screen to be edge to edge with full margins ).

The problem description in full details in the following pictures.

## Information

![test](https://user-images.githubusercontent.com/47486787/53685937-da7ba300-3d29-11e9-8697-ccfdf7df87d3.jpg)
![test2](https://user-images.githubusercontent.com/47486787/53685936-d9e30c80-3d29-11e9-808c-12afc72c043f.jpg)

### Command or Code

cordova.InAppBrowser.open('https://www.google.com', '_blank', 'location=no,usewkwebview=yes')

set yes to option usewkwebview.

### Environment, Platform, Device

iPhone x with latest 12.1.4 ios

### Version information

cordova cli 9
cordova-plugin-inappbrowser master version

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by filippodicostanzo** [comment] 2019-05-15 11:12
same issue. someone has solved this bug?

**Comment by mosababubakr** [comment] 2019-08-19 15:13
This issue not solved until now !!!!

no any one can solve this big problem ???

where are you programmers ?

**Comment by jcesarmobile** [comment] 2019-10-16 23:48
Closing as duplicate of https://github.com/apache/cordova-plugin-inappbrowser/issues/301

**Closed by jcesarmobile** 2019-10-16 23:48 UTC
Labels: bug, platform: ios
