### ISSUE TITLE
cordova-plugin-inappbrowser does not work with latest cordova-ios 5.1.0. build fails with error "Unknown type name 'CDVUIWebViewDelegate'" 

### ISSUE THREAD

**Issue by rajashekaranugu** [apache/cordova-plugin-inappbrowser#587] opened 2019-12-02 17:37 UTC
# Bug Report

## Information
As every one is aware of the the deprecated API issue and warning email from apple in regards to usage of 'UIWebView' in ANY form in the App. I was trying to build the app using the instructions provided at "https://ionicframework.com/blog/understanding-itms-90809-uiwebview-api-deprecation/"

-using cordova-ios 5.1.0
-<preference name="WKWebViewOnly" value="true"/> then cordova prepare ios
-ionic-web-view 4.1.2
-@ionic-native/in-app-browser 3.1.0 - "https://ionicframework.com/..."

While building am getting errors, which is related to inAppBrowser.
Error: "Unknown type name 'CDVUIWebViewDelegate'". seems like this plugin still using UIWebview class.

1) How can I solve this?
    Do I need to replace the above inAppBrowser Plugin with "@ionic-enterprise/inappbrowser".
    Am not on enterprise plan though.
2) What are the differences between these two inAppBrowser plugins?
3) Also am updating ionic-webView plugin from 1.2.1 to 4.1.2 and losing local storage, do we have
any solution for this?

Really appreciate your help and time

Best
Raj

**Comment by breautek** [comment] 2019-12-02 17:43
Duplicate of https://github.com/apache/cordova-plugin-inappbrowser/issues/583

But to quickly answer your question, `inappbrowser` still depends on UIWebview code and there is no official solution yet, but it is an issue that is known.

https://github.com/apache/cordova-plugin-inappbrowser/pull/584 may help you work around this issue temporarily.

https://github.com/apache/cordova-discuss/pull/110 may peak your interest as well.

**Closed by breautek** 2019-12-02 17:43 UTC

**Comment by breautek** [comment] 2019-12-02 17:47
Regarding `@ionic-enterprise/inappbrowser` you may need to consult with someone who is more familiar with ionic on how you can use a pending cordova PR. I'm not familiar enough with the ionic framework to tell you if the package can simply be substituted/merged.

Also note that there is no guarantee that PR will land in master.

**Comment by rajashekaranugu** [comment] 2019-12-02 17:52
@breautek thanks for the replay, sure will follow #584
