### ISSUE TITLE
local variable inAppWebView is accessed from within inner class; needs to be declared final

### ISSUE THREAD

**Issue by Abbo44** [apache/cordova-plugin-inappbrowser#836] opened 2021-01-06 14:12 UTC
# Bug Report

### What is expected to happen?
Build works.

### What does actually happen?
Build fail: 
`PROJECT\cordova\platforms\android\src\org\apache\cordova\inappbrowser\InAppChromeClient.java:163: error: local variable inAppWebView is accessed from within inner class; needs to be declared final
                     inAppWebView.loadUrl(request.getUrl().toString());
                    ^
PROJECT\cordova\platforms\android\src\org\apache\cordova\inappbrowser\InAppChromeClient.java:169: error: local variable inAppWebView is accessed from within inner class; needs to be declared final
                         inAppWebView.loadUrl(url);
                         ^
`

## Information
We haven''t problems with release 4.0.0

### Version information
The library our team are using:
"dependencies": {
    "cordova-android": "^6.4.0",
    "cordova-android-support-gradle-release": "^1.4.7",
    "cordova-browser": "^5.0.4",
    "cordova-custom-config": "5.0.3",
    "cordova-ios": "^4.5.5",
    "cordova-plugin-advanced-http": "^2.2.0",
    "cordova-plugin-browsertab": "^0.2.0",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-customurlscheme": "^4.4.0",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-inappbrowser": "4.0.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.2",
    "cordova-plugin-network-information": "^1.3.4",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-sqlite-storage": "^2.3.1"
  }

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jhlee8804** [comment] 2021-01-11 09:27
+1

**Comment by Lbob552** [comment] 2021-01-15 14:13
+1

**Comment by timbru31** [comment] 2021-01-15 14:26
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by breautek** [comment] 2021-01-15 14:50
I'm unable to reproduce the build error with with cordova-android@9.

I also tested cordova-android@6.4.0 and did reproduce the issue. This suggests there is some incompatibility between old build tools vs modern build tools.

Generally speaking, we do not support older versions of our platforms. So I'll be closing this issue as won't do / won't fix.

Potential workarounds:
- Upgrade cordova-android to the latest version if possible.
- If upgrading cordova-android is not possible, then you may need to fork and patch this plugin yourself.

**Closed by breautek** 2021-01-15 14:50 UTC
