### ISSUE TITLE
Can't build on Cordova iOS@6.0.0

### ISSUE THREAD

**Issue by jay34fr** [apache/cordova-plugin-inappbrowser#719] opened 2020-06-06 21:07 UTC
Hi all,

I try to update to Cordova iOS@6.0.0 and I can't build my app without uninstalling the Inappbrowser plugin.

The error message :

The following build commands failed:
	CompileC /Users/xxxxxxxxxxxxxx/Objects-normal/arm64/CDVWKInAppBrowser.o /Users/xxxxxxxxx/platforms/iOS/xxxxxx/Plugins/cordova-plugin-inappbrowser/CDVWKInAppBrowser.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65

Thx in advance.

**Comment by timbru31** [comment] 2020-06-06 21:16
Duplicate of #709

**Closed by timbru31** 2020-06-06 21:16 UTC
