### ISSUE TITLE
Plugin doesn't install correctly

### ISSUE THREAD

**Issue by rafaelmb** [apache/cordova-plugin-inappbrowser#354] opened 2018-11-23 13:46 UTC
Hi, when I try to install the plugin I got no error messages but the plugin doesn't work on android. Debugging my app I got this error messages (on logcat):
`
11-23 11:24:03.776 6694-6770/com.example.hello W/System.err: java.lang.ClassNotFoundException: org.apache.cordova.inappbrowser.InAppBrowser
`
 Searching around I can see that the plugin is downloaded but the .java files aren't going to \platforms\android\CordovaLib\src\org\apache\cordova folder (res images are going normal).  So I've tried the same steps and the error happens on a clean cordova install. The environment is on a windows 10 machine:

```
cordova -v
8.1.2 (cordova-lib@8.1.1)
```

```
cordova platform ls
Installed platforms:
  android 7.1.3
```

Copying the 3 .java files to the folder and building again make the plugin work.

**Comment by janpio** [comment] 2018-11-23 13:51
This is caused by the same bug as https://github.com/apache/cordova-android/issues/574
Bugfix has been merged and we are working on a release, expect cordova-android 7.1.4 shortly.

**Closed** 2018-11-23 13:53 UTC
Labels: bug, duplicate

**Comment by rafaelmb** [comment] 2018-11-23 15:40
Thank you.
