### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by vespino** [apache/cordova-plugin-inappbrowser#325] opened 2018-10-22 12:49 UTC
On iPhone X and higher the inappbrowser looks like this (I'm referring to the status bar):

![img_0108](https://user-images.githubusercontent.com/6991325/47292926-d49de480-d608-11e8-889a-d9301826ee31.PNG)

I have added the new splashscreen image and the app itself looks great. Is there a way to fix this?

Is there also a way to keep the content of the inappbrowser from going under the "homebar"?

![img_0107](https://user-images.githubusercontent.com/6991325/47293140-8ccb8d00-d609-11e8-87bc-a513f7e982eb.PNG)

Phonegap uses "constant(safe-area-inset-bottom)" and "env(safe-area-inset-bottom)" for this.

**Comment by cvanem** [comment] 2018-10-22 16:50
I am also having this issue on an iPhone XS.  The status bar looks fine in the Cordova webview (using cordova- plugin-statusbar).  After the inappbrowser is opened the status bar appears incorrect.  I would also expect the status bar area to be hidden when the phone is in landscape mode.  

Here is how it looks in portrait mode:

![potrait](https://user-images.githubusercontent.com/24579103/47305410-9bed1380-d5e6-11e8-8631-eff8798b1b70.png)

This is landscape.  The status bar text is gone, but the area is still offset.  This area should not be displayed when in landscape mode.

![landscape](https://user-images.githubusercontent.com/24579103/47305409-9bed1380-d5e6-11e8-9541-f5c7410f4f13.png)

This is how I would expect it to look and how it looks in the Cordova webview: 
![expected](https://user-images.githubusercontent.com/24579103/47305436-ac04f300-d5e6-11e8-9aad-03588fb8cc30.png)

I have had some success by manually setting the STATUSBAR_HEIGHT to 0 in the CDVInAppBrowser.m file, but this then requires the padding to be implemented in user space and does not allow altercations to the text color.

It would be nice if the inappbrowser inherited the settings from the Cordova WebView using cordova-plugin-statusbar.  

Has anyone found a solution other than modifying the source code?

**Comment by vespino** [comment] 2018-10-25 12:29
@cvanem I'm using this fork of themeable browser now: https://github.com/toontoet/cordova-plugin-themeablebrowser.git

**Comment by mosababubakr** [comment] 2019-02-15 17:43
Hello,

I face the same problem when testing on iphone x, and works fine on older iphone like iphone 7.

Testing on iphone 7 plus without any issues, just i face this issue on iphone x.
Using Cordova inappbrowser master version.

@dpa99c  can you please test on iphone x to see this issue ?

Regards

**Comment by dpa99c** [comment] 2019-02-15 18:12
I have patched [a fix](https://github.com/dpa99c/cordova-plugin-inappbrowser-popup-bridge/commit/fb6c0cd4a9f774ddf5e2badc40339afd8ad2a746) which resolves this issue for iPhone X family devices into a fork of this plugin ([cordova-plugin-inappbrowser-popup-bridge](https://github.com/dpa99c/cordova-plugin-inappbrowser-popup-bridge)).

When I have time, I will back patch it to this plugin (or someone else can do it before me).

**Comment by mosababubakr** [comment] 2019-02-15 18:20
Hello @dpa99c ,
Thanks for reply,

We wait your fix.

thanks

Regards.

**Comment by mosababubakr** [comment] 2019-02-19 17:24
Hello @dpa99c 

I try to use ([cordova-plugin-inappbrowser-popup-bridge](https://github.com/dpa99c/cordova-plugin-inappbrowser-popup-bridge)). but this plugin have an 2 issues:
1- The prvious issue in master version that you solved still appear in this popup-bridge plugin.
2- if you try to open inappbrowser and using the option hidden=yes, the status bar become light grey before the window appear. In other word: ( if your design is dark, and you are using the option hidden=yes, the status bar will be light before the browser window appear and before loadstop fired ).
In usual it should take the effect after loadstop fire as version 3.0.0.

So to solve this issue, you should make the status bar in light color after load stop complete.

I hope these information will help to solve this issue, and from now after you solving this issue as well, I think there will be no any issues for the master version.

Thanks again for solving old issues, and we hope from you to solve this issue as soon as possible.

Regards

**Comment by mosababubakr** [comment] 2019-03-01 21:12
Hello @dpa99c ,
I test inappbrowser plugin master version in my iphone X, I capture 2 screenshots for landscape and portrait mode, so, can you please confirm if your fix for popup bridge plugin solve these issues in the following pictures?

Portrait mode:

![test](https://user-images.githubusercontent.com/47486787/53666468-d8a4d780-3c76-11e9-8f91-7e5bb4e8a40f.jpg)

Landscape mode:

![test2](https://user-images.githubusercontent.com/47486787/53666467-d80c4100-3c76-11e9-9623-d7eddf0b0b6a.jpg)

So, if your fix for popup bridge solving those issues, can you please fix the master version of the plugin cordova-inappbrowser 

Thanks 
Regards

**Comment by dpa99c** [comment] 2019-03-04 16:29
@mosababubakr 

> 1- The prvious issue (#424) in master version that you solved still appear in this popup-bridge plugin.

The fix which I committed to `cordova-plugin-inappbrowser` for #424 has not been merged into `cordova-plugin-inappbrowser-popupbridge`.

Note that `cordova-plugin-inappbrowser-popupbridge` is a fork which I created for my own specific needs, so is not a fully maintained fork of this plugin.

> 2- if you try to open inappbrowser and you are using the option hidden=yes, and your background is dark and using preference name="StatusBarStyle" value="blacktranslucent" , then: the status bar become in light color before the window appear (before inappbrowser.show) take action.

Status bar color is not an issue for me because in the app in which I use `cordova-plugin-inappbrowser-popupbridge` in production, the main app status bar colour is also light so matches the inappbrowser.

> (in master version the status bar work correctly, but it conflict with upper side in inappbrowser).

`cordova-plugin-inappbrowser-popupbridge` has been fixed so that the statusbar height is set to the default and only works if `cordova-plugin-statusbar` is also present (which it is in my app). It has the effect of making the statusbar height 40px on iPhone X family devices and 20px non-iPhone X family, which resolves the issue in my app:

<img width="300" src="https://user-images.githubusercontent.com/2345062/53746628-87286280-3e99-11e9-9949-ee1d7c223633.png" />
<img width="300" src="https://user-images.githubusercontent.com/2345062/53746734-c060d280-3e99-11e9-8425-e98268a89023.png"/>

However, this statusbar is also applied in landscape orientation, which is fine for non-iPhone X family, but means on iPhone X family the status is displayed when it should be hidden (as it is in the main app Webview by `cordova-plugin-statusbar`):

<img width="500" src="https://user-images.githubusercontent.com/2345062/53746923-12095d00-3e9a-11e9-8827-9e8ff202b38c.png"/>
<img width="500" src="https://user-images.githubusercontent.com/2345062/53746925-12a1f380-3e9a-11e9-98a0-00e7d503a524.png"/>


This is not a problem for me as my app is fixed in portrait, however it could do with fixing for generic use.

The above screenshots have been created using the [`iphonex` branch of my `cordova-plugin-inappbrowser-popup-bridge-test` test app ](https://github.com/dpa99c/cordova-plugin-inappbrowser-popup-bridge-test/tree/iphonex).

**Comment by mosababubakr** [comment] 2019-03-04 16:36
@dpa99c 

Thanks for explain.

Anyway,
I think your fix for cordova-plugin-inappbrowser-popup-bridge can be applied to the master version will make a good sense.

Thanks 

Regards

**Comment by dpa99c** [comment] 2019-03-04 16:38
@mosababubakr I will first try to fix `cordova-plugin-inappbrowser-popup-bridge` so that the statusbar is hidden in landscape. Then I'll port those changes back to this plugin via a PR. Hopefully I can get this done in the next week or so.

**Comment by mosababubakr** [comment] 2019-03-04 16:49
@dpa99c 

If you can also fix the margins in landscape, please refer to the following picture to see the issue.

![53685936-d9e30c80-3d29-11e9-808c-12afc72c043f](https://user-images.githubusercontent.com/47486787/53747998-1b4ff500-3ead-11e9-81e2-320617335073.jpg)

To fix the issue, please open Safari in iphone x  in landscape mode and try to open any website, you will see that the margin is safe and the camera not make the content hidden.

Regards

**Comment by dpa99c** [comment] 2019-03-04 17:04
This needs to be addressed using the `safe-area-inset` constants within your CSS: if I were to modify the plugin to add that padding natively, then you would have a big grey bar on the left instead of your blue background color from your CSS.

The [`iphonex` branch of my `cordova-plugin-inappbrowser-popup-bridge-test` test app ](https://github.com/dpa99c/cordova-plugin-inappbrowser-popup-bridge-test/tree/iphonex) illustrates how this can be done:

<img width="500" src="https://user-images.githubusercontent.com/2345062/53749519-74189100-3e9f-11e9-8304-b76c7bd8336a.png" />

See [Designing Websites for iPhone X](https://webkit.org/blog/7929/designing-websites-for-iphone-x/) for an explanation of safe area insets.

**Comment by mosababubakr** [comment] 2019-03-04 17:39
@dpa99c 

I know that safe-area-inset can be used in the main cordova webview, but for standard method, inappbrowser should work as Safari work for ios devices, so, because inappbrowser main purpose to load external websites, you can't control all websites, so, it is a nice idea to make inappbrowser uses safe margins in landscape mode only for iphone x devices.

Anyway, this is not a big problem, it is just make a better impression to the users.

And, from now, most companies start to make phone devices to be full margins, like: iphone x family devices, samsung galaxsy s10 devices...... etc.

Regards

**Comment by dpa99c** [comment] 2019-03-05 15:33
I've had a go a fixing this so the status bar is hidden in landscape and shown in portrait orientation, but the changes require an understanding of the native iOS view hierarchy (mine is minimal and I don't have the need to expand it), so I'm going to have to leave this to someone with more native iOS UI experience.

An ideal fix would work both with `cordova-plugin-statusbar` being present and not present.

To automatically set the background color of the status bar in the inappbrowser window to the same as that specified in `cordova-plugin-statusbar` would requires changes to `cordova-plugin-statusbar` to publicly expose its settings so this plugin could read them. It would be much simpler just to allow the status bar color to be specified as an option in this plugin and the host app can then pass the same color value to both `cordova-plugin-statusbar` and this plugin, and similarly allow programmatic show/hide of the status bar (as `cordova-plugin-statusbar` does). In essence, a port of the functionality from `cordova-plugin-statusbar` to this plugin.

**Comment by mosababubakr** [comment] 2019-03-05 15:40
@dpa99c 

So, now, I think the only big problem need to be solved to fix the status bar height in master version of inappbrowser.

Regards

**Comment by dpa99c** [comment] 2019-03-05 15:45
> @dpa99c
> 
> So, now, I think the only big problem need to be solved to fix the status bar height in master version of inappbrowser. (portrait mode)
> 
> Regards

that at least I think I can help with: it's currently hard-coded at 20px on master of this plugin, so I can at least bring that across the change from popupbridge as a PR which applies the device-specific value.
but the orientation change stuff is beyond me 😒

**Comment by mosababubakr** [comment] 2019-03-07 21:08
@dpa99c

I check safari app in landscape mode at iphone x, there is no status bar appear.

So inapbrowser should remove grey bar in landscape mode as safari, instead of grey bar.

Regards

**Comment by dpa99c** [comment] 2019-03-08 09:03
@mosababubakr that's also what `cordova-plugin-statusbar` does to the main Cordova app Webview when installed, but I have been unable to so far translate that behaviour to the Inappbrowser Webview (due to my limited experience with native iOS UI components/view hierarchy). 

I've had a go at setting the correct statusbar height in portrait in this plugin (as my popupbridge fork now does) but there must be some difference now between them, because the code that works in popupbridge does not work when I translate it to this plugin. When I have time, I will investigate further. Or hope that someone with more native iOS UI experience picks up this issue and fixes it before me 😀

**Comment by mosababubakr** [comment] 2019-03-28 00:42
@dpa99c 

I found that if you set usewkwebview=yes, then status bar will overlays the main view and distort it, and also, for landscape view if you set usewkwebview=yes, then the screen for iphone x not fit correctly, so, i back to default behavior (aka usewkwebview=no) or omit this option.

So, if you tend to complete support the option usewkwebview=yes, then I think you can improve this option to fit and work correctly for iphone x, you can rebuild this option by check the default code, as usewkwebview=no work.

Regards

**Comment by KishoreKoushik** [comment] 2019-08-05 12:58
Hi @dpa99c ,may I know when this fix will be merged to master of inappbrowser?

**Comment by KishoreKoushik** [comment] 2019-08-06 05:24
@dpa99c 

When will you be pushing this fix to the master?

**Comment by dpa99c** [comment] 2019-08-06 05:27
@KishoreKoushik I've not been able to fix this issue (see my comment above)

**Comment by KishoreKoushik** [comment] 2019-08-06 05:59
@dpa99c But I used, cordova-plugin-inappbrowser-popup-bridge and I don't see the overlap issue anymore. The what is the issue with the above plugin

**Comment by dpa99c** [comment] 2019-08-06 06:45
[dpa99c commented on 8 Mar](https://github.com/apache/cordova-plugin-inappbrowser/issues/325#issuecomment-470856262)

> I've had a go at setting the correct statusbar height in portrait in this plugin (as my popupbridge fork now does) but there must be some difference now between them, because the code that works in popupbridge does not work when I translate it to this plugin.

I've not been able to translate that code from popupbridge IAB to this plugin and get it working.
And right now I don't have the time to try again.
But this is open-source software so you are welcome to try fixing it yourself 😀

**Comment by mosababubakr** [comment] 2019-08-19 15:13
This issue not solved until now !!!!

no any one can solve this big problem ???

where are you programmers ?

**Comment by mosababubakr** [comment] 2019-09-25 10:52
@dpa99c  Hello,

Is there any solution for this issue ?

I think iphone x family devices and upper versions still face this issue.

**Comment by mosababubakr** [comment] 2019-09-25 15:28
@dpa99c 
Could you please take a look to this comment please:

https://github.com/apache/cordova-plugin-inappbrowser/issues/301#issuecomment-452220131

**Comment by dpa99c** [comment] 2019-09-25 15:30
@mosababubakr I'm busy with many other things at the moment - when I have time, I'll take a look

**Comment by jacobweber** [comment] 2019-10-01 17:15
See also: https://issues.apache.org/jira/browse/CB-13583

**Comment by edskeizer** [comment] 2019-11-18 14:40
I have altered the `CDVInAppBrowserNavigationController.m` in this repo, which works in my project. It seems the double bar is created when the device has the Dark mode option set to 'on'. In my code I have set the height of the statusbar to 44 when it is a device with a notch.

https://github.com/edskeizer/cordova-plugin-inappbrowser/commit/01f1b5e8f3c14e2187184cf191ea0ee4d6498e93

**Comment by jcesarmobile** [comment] 2020-04-11 14:18
closing as duplicate of https://github.com/apache/cordova-plugin-inappbrowser/issues/301

**Closed by jcesarmobile** 2020-04-11 14:18 UTC
Labels: bug, platform: ios, wkwebview
