### ISSUE TITLE
The browser is not compatible with iPhone X when the option usewkwebview=yes

### ISSUE THREAD

**Issue by iphonedeveloper99** [apache/cordova-plugin-inappbrowser#454] opened 2019-03-24 15:36 UTC
# Bug Report

## Problem
inappbrowser  is not compatible with iphonex if you set usewkwebview=yes, specially the status bar is overlaps the upper side interface layout.
### What is expected to happen?
the browser interface layout must set correctly to fit iphone x display.

### What does actually happen?
var ref = cordova.InAppBrowser.open('http://apache.org', '_blank', 'location=yes,usewkwebview=yes');
try to open previous link in iphone x device, and look at the top, you will notice a big problem, (the status bar is overlaps the upper side interface layout.)

## Information

var ref = cordova.InAppBrowser.open('http://apache.org', '_blank', 'location=yes,usewkwebview=yes');
Try to use iphonex with ios 12.1.4 for testing to see the results.

### Command or Code

var ref = cordova.InAppBrowser.open('http://apache.org', '_blank', 'location=yes,usewkwebview=yes');
(usewkwebview=yes)

### Environment, Platform, Device

iphone x family device

### Version information

cordova cli 9.0
cordova-plugin-inappbrowser master version
ios ver 12.1.4

## Checklist

- [ ] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpa99c** [comment] 2019-03-28 07:18
Duplicate of #325

**Comment by jcesarmobile** [comment] 2020-04-11 14:19
duplicate of https://github.com/apache/cordova-plugin-inappbrowser/issues/301 too

**Closed by jcesarmobile** 2020-04-11 14:19 UTC
Labels: bug, duplicate, platform: ios, wkwebview
