### ISSUE TITLE
InAppBrowser causes issues with MSApp's printing API

### ISSUE THREAD

**Issue by J-Lowe** [apache/cordova-plugin-inappbrowser#488] opened 2019-06-11 22:08 UTC
​
​
### Issue Type​
​
​
- [x] Bug Report​
- [ ] Feature Request​
- [ ] Support Question​
​
## Description​
After opening and closing the InAppBrowser, the MSApp printing API throws an error in the system file edgehtml.dll.  More specifically, when using MSApp.getHtmlPrintDocumentSourceAsync() after opening and closing the InAppBrowser, this error is thrown ​
```​
Unhandled exception at line 357, column 1 in res://edgehtml.dll/preview.js​
​
0x8000ffff - JavaScript runtime error: Unexpected call to method or property access.​
```
​
This error is mentioned to have been fixed [here on the Microsoft Developer forums](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17148061/), however that only applies to printing from the Edge browser itself.​
​
## Information​
​
This bug was first noticed in an enterprise app using Ionic and Cordova, but was able to be reproduced in a standalone Cordova app.  Our app calls InAppBrowser at launch, so it is always running into this issue.  The standalone app used for testing was set up to call InAppBrowser on demand, and it was shown that the issue only arose after InAppBrowser was opened and then closed before printing.​
​
### Command or Code​
​
To reproduce this issue, I used the Windows Sample printing app's [scenario1basic.js](https://github.com/microsoft/Windows-universal-samples/blob/win10-1607/Samples/Printing/js/js/scenario1basic.js) in a new Cordova app.  Here are the modified files:​
​
index.html:​
```​
<!DOCTYPE html>​
<html>​
<head>​
    <meta charset="utf-8">​
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">​
    <script type="text/javascript" src="/www/WinJS/js/base.js"></script>​
    <script src="cordova.js"></script>​
    <script type ="text/javascript" src="js/print.js"></script>​
</head>​
<body>​
    <p><button id="printButton">Test Print</button></p>​
    <p><button id="browserButton">Open Browser</button></p>​
</body>​
</html>​
```
print.js:​
```​
(function () {​
    "use strict";​
​
    var printManager = Windows.Graphics.Printing.PrintManager.getForCurrentView();​
    var page = WinJS.UI.Pages.define("index.html", {​
        ready: function (element, options) {​
            var printButton = document.getElementById("printButton");​
            var browserButton = document.getElementById("browserButton");​
​
            if (!Windows.Graphics.Printing.PrintManager.isSupported()) {​
                WinJS.log && WinJS.log("Printing is not supported.", "sample", "error");​
                // Hide the Print button if printing is not supported.​
                printButton.style.display = "none";​
            }​
​
            printButton.addEventListener("click", printButtonHandler, false);​
            browserButton.addEventListener("click", browserButtonHandler, false);​
​
            // Register for Print Contract​
            printManager.addEventListener("printtaskrequested", onPrintTaskRequested);​
        },​
        unload: function () {​
            printManager.removeEventListener("printtaskrequested", onPrintTaskRequested);​
        }​
    });​
​
    /// <summary>​
    /// Print event handler for printing via the PrintManager API.​
    /// </summary>​
    /// <param name="printEvent" type="Windows.Graphics.Printing.PrintTaskRequest">​
    /// The event containing the print task request object.​
    /// </param>​
    function onPrintTaskRequested(printEvent) {​
        var printTask = printEvent.request.createPrintTask("Print Sample", function (args) {​
            var deferral = args.getDeferral();​
            // Register the handler for print task completion event​
            printTask.addEventListener("completed", onPrintTaskCompleted);​
            MSApp.getHtmlPrintDocumentSourceAsync(document).then(function (source) {​
                args.setSource(source);​
                deferral.complete();​
            });​
        });​
    }​
​
    /// <summary>​
    /// Print Task event handler is invoked when the print job is completed.​
    /// </summary>​
    /// <param name="printTaskCompletionEvent" type="Windows.Graphics.Printing.PrintTaskCompleted">​
    /// The event containing the print task completion object.​
    /// </param>​
    function onPrintTaskCompleted(printTaskCompletionEvent) {​
        // Notify the user about the failure​
        if (printTaskCompletionEvent.completion === Windows.Graphics.Printing.PrintTaskCompletion.failed) {​
            WinJS.log && WinJS.log("Failed to print.", "sample", "error");​
        }​
    }​
​
    function printButtonHandler() {​
        // If the print contract is registered, the print experience is invoked.​
        Windows.Graphics.Printing.PrintManager.showPrintUIAsync();​
    }​
​
    function browserButtonHandler() {​
        cordova.InAppBrowser.open("google.com", "_blank");​
    }​
​
})();​
```
Create a new Cordova app, modify index.html as shown above, and then create print.js in the js folder with the above code.  Clicking the Test Print button first will show a correct printing dialog. Clicking the Open Browser button, closing the InAppBrowser, and then clicking the Test Print button will throw the error from edgehtml.dll.​
​
### Environment, Platform, Device​
​
Environment/Platform: Windows 10​
Devices: Dell Latitude E6540, HP ElitePOS Mobile​
​
### Version information​
​
Windows: 10.0.17763 Build 17763​
Cordova: 6.5.0​
InAppBrowser\*: 1.7.2 and 3.0.0​
(Optional) Ionic Framework: 3.19.1​
(Optional) Visual Studio: 2015​ professional
​
\*Note: InAppBrowser version 1.7.2 is the version currently used in our enterprise app.  Version 3.0.0 was the most recent version used in the standalone testing app.  Both cause this issue.​
​
​
## Checklist​
​
​
- [x] I searched for already existing GitHub issues about this​
- [ ] I updated all Cordova tooling to their most recent version​
- [x] I included all the necessary information above​

**Comment by nsandeep87** [comment] 2019-07-16 05:59
I see this issue on performing the following steps:
1. Open the inappbrowser
2. Close the the inappbrowser ( ref.close())
3. Try to invoke Windows.Graphics.Printing.PrintManager.showPrintUIAsync();
4. I get the error Unhandled exception at line 357, column 1 in res://edgehtml.dll/preview.js​

However if I hide the inappbrowser, instead of close it, the issue is not reproducible.
1. Open the inappbrowser
2. Hide the the inappbrowser ( ref.hide())
3. Try to invoke Windows.Graphics.Printing.PrintManager.showPrintUIAsync();
4. I get the error Unhandled exception at line 357, column 1 in res://edgehtml.dll/preview.js​

**Comment by erisu** [comment] 2022-12-19 13:17
[Cordova Windows](https://github.com/apache/cordova-windows) has been deprecated and is no longer supported making this issue obsolete.

**Closed by erisu** 2022-12-19 13:17 UTC
Labels: bug, platform: windows
