### ISSUE TITLE
App freezing after opening the InAppBrowser on specific URLs / Inputs

### ISSUE THREAD

**Issue by alan-grixti** [apache/cordova-plugin-inappbrowser#296] opened 2018-09-11 13:46 UTC
I would like to bring to attention an issue (I believe it's a bug, could be wrong) which I've come across. I believe it is easy to reproduce, and managed to successfully reproduce it repeatedly myself on a test environment. Zip file linked bottom of issue containing the test environment. GIF showing the issue added below.

In brief, the problem is that on some particular sites, whenever navigation / keyboard is triggered in the InAppBrowser window, it is causing the underlying application to freeze and become unresponsive to any user actions.

Environment: Cordova 8, iOS 4.5.5 and Ionic 3
Affected Platform : iOS
Versions: iOS v11.4
Devices Affected: iPhone 5 up to 6S/Plus

Steps to reproduce:

1. Create a blank project (Ionic, whatever flavour you prefer).
2. Add reference to the InAppBrowser plugin
3. Run use case below:

- Open https://www.google.com in InAppBrowser
- Locate the search bar on the page and type something.
- Click / tap outside of the search bar
- Close the InAppBrowser instance
- App will be unresponsive

![ezgif com-gif-maker](https://user-images.githubusercontent.com/5612762/45364200-ce642380-b5d9-11e8-950a-2e143d574c14.gif)

Link to test environment : [iab-test.zip](https://github.com/apache/cordova-plugin-inappbrowser/files/2371184/iab-test.zip)

**Comment by alan-grixti** [comment] 2018-09-11 14:14
Hi, yes. I have ran into that too. However could not pin point an exact trigger.

**Comment by PieterVanPoyer** [comment] 2018-09-11 14:27
I am currently using a fork of the plugin, so it is possibly related to a development commit.
You seem to be using the version 3.0.0 for this.

**Comment by alan-grixti** [comment] 2018-09-11 14:32
At first I was using a fork of this which I created myself for development purposes, mostly dealing with the iPhone X's status bar not being handled as gracefully as desired by the plugin. And that's where I stumbled upon this issue. However, I reverted back to version 3.0.0 and saw that this behavior is present in it too.

**Comment by PieterVanPoyer** [comment] 2018-09-11 14:36
In my app I have next line [tmpWindow setWindowLevel:baseWindowLevel+1]; from
https://github.com/apache/cordova-plugin-inappbrowser/commit/dc5329d15757cca1c327e87a309fddbb58e554ed 
I changed it back again to [tmpWindow setWindowLevel:UIWindowLevelNormal];
the old code and it works. (See line 245 of CDVInAppBrowser.m )

We are using the WebView and not yet the WkWebview. But in your zip file the line is still the old one.

**Comment by alan-grixti** [comment] 2018-09-11 14:45
So basically if I revert commit `dc5329d`, the mentioned issue would be fixed?

**Comment by PieterVanPoyer** [comment] 2018-09-11 15:29
I think you should try it. But you have to be sure the line is out of the xcode project. So rebuild it after the revert by removing and adding the platform I think.

**Comment by alan-grixti** [comment] 2018-09-12 07:50
Hi Pieter, tried it but unfortunately the freezing still occurs.

**Comment by PieterVanPoyer** [comment] 2018-09-12 08:00
Today I will be working on it a little bit. Maybe you could try to use the 2.x version (latest stable 2 version).
Does that solve your problem?

**Comment by alan-grixti** [comment] 2018-09-12 14:44
Sadly no, this issue is still present in version 2.0.2.

**Comment by PieterVanPoyer** [comment] 2018-09-19 10:37
Is this issue still present? For me the reverting of one code line solved the problem.
If it is still present. Can you send or zip your Plugins folder of your Xcode project. (The Plugins folder in the platform/ios/YourProject/Plugins ) But make sure the issue is still present in the project.

**Comment by alan-grixti** [comment] 2018-09-19 12:36
I can reproduce it from my iPhone 5s. I don't know if I'm doing something wrong myself at this point. Thanks for your patience Pieter. Compressed below are the complete iOS project and the plugins folder as requested. Right now it's running the 3.0.0 version with the specified line mentioned before changed manualy.

Thanks for your patience @PieterVanPoyer .

[ios.zip](https://github.com/apache/cordova-plugin-inappbrowser/files/2397035/ios.zip)
[Plugins.zip](https://github.com/apache/cordova-plugin-inappbrowser/files/2397036/Plugins.zip)

**Comment by jacobg** [comment] 2018-10-11 19:14
I'm having this problem on version 2.0.2, and I applied the following commit fix (not on npm yet) and it works fine:   https://github.com/apache/cordova-plugin-inappbrowser/pull/272/files

Does that fix not work for you?

**Comment by jcesarmobile** [comment] 2018-10-13 19:42
Closing as duplicate of https://github.com/apache/cordova-plugin-inappbrowser/issues/314, despite it's older, it has a PR already.
Anyway, I think https://github.com/apache/cordova-plugin-inappbrowser/pull/272 should have fixed it.

**Closed** 2018-10-13 19:42 UTC
Labels: platform: ios, support

**Comment by iAmAnkeeta** [comment] 2019-02-07 03:28
@jcesarmobile Any updates on when the plugin will be released with the fixes?

**Comment by jcesarmobile** [comment] 2019-02-07 08:06
No

**Comment by vavanish** [comment] 2019-08-23 14:52
Any updates on this issue?
