### ISSUE TITLE
customscheme event not fire after call with _system

### ISSUE THREAD

**Issue by boynet** [apache/cordova-plugin-inappbrowser#358] opened 2018-11-28 19:13 UTC
my use case: allow inappbrowser to have links to whatsapp api like: `whatsapp://send?text=hello`
so I add into config.xml:
`<preference name="AllowedSchemes" value="whatsapp" />`

inappbrowser script:
```
let inAppBrowser = cordova.InAppBrowser.open(url, '_blank');
inAppBrowser.addEventListener('customscheme', onCustomscheme);
onCustomscheme(event){
        window.open(event.url, "_system");
    }
```

the bug is after any calling to `window.open(event.url, "_system");` or `cordova.InAppBrowser.open(event.url, '_system');` the customscheme event no longer firing no matter what.

so the first click on the `whatsapp://send?text=hello` link will fire the customscheme and open whatsapp, after getting back into the app and clicking the link again the customscheme no longer fire.

I checked it with multipile scheme not only whatsapp and all of them acts the same(so even if the customscheme does nothing)

**Comment by janpio** [comment] 2018-11-28 20:11
I think with `_system` a lot of the functionality does not work as we handed off control to the external app.

What platform are you testing with?

**Comment by boynet** [comment] 2018-11-28 20:18
on android
so how can I make the whatsapp call correctly? is there any other way of firing the system deep link handling than doing  `window.open("whatsapp://send?text=hello", "_system"); or cordova.InAppBrowser.open("whatsapp://send?text=hello", '_system');`

**Comment by nnimis** [comment] 2020-06-21 22:33
There is a workaround for this issue, would it be possible to have it as a fix on any version? https://stackoverflow.com/questions/31863998/cordova-share-via-whatsapp-from-a-click-inside-webview

**Comment by boynet** [comment] 2024-09-12 13:11
for anyone here there is better way to solve it now:
enable the beforeload event
*  inAppBrowserRef = cordova.InAppBrowser.open(url, '_blank', 'beforeload=yes');

register to the event

* inAppBrowserRef.addEventListener('beforeload', beforeloadCallBack);

now for example here is a code that open any link that not start with https http or // with the device browser
```
  beforeloadCallBack(params,callback){
        let url = params.url;
        //if it start with // http or https
        if (url.match(/^(https?:)?\/\//)) {
            callback(params.url);
        } else {
            //let it naturally open by the system so do nothing
        }

    }
```

I am not really sure if we still need to add them to AllowedSchemes its undocumented

**Comment by breautek** [comment] 2024-09-12 15:20
I'm closing this as not a bug.

It's documented that `addEventListener` and registering for events requires `_blank` and will not work with other open modes. See https://github.com/apache/cordova-plugin-inappbrowser?tab=readme-ov-file#inappbrowseraddeventlistener

**Closed by breautek** 2024-09-12 15:20 UTC
Labels: support, platform: android
