### ISSUE TITLE
[Android] Statusbar disappear after inappbrowser window opened (go in full screen)

### ISSUE THREAD

**Issue by mosabab** [apache/cordova-plugin-inappbrowser#598] opened 2019-12-28 17:56 UTC
# Bug Report

### What is expected to happen?
The statusbar should appear after inappbrowser appear, as in iOS, and not go into full screen mode, the code must set an option __fullscreen__ and the user choose between `true` or `false`

### What does actually happen?
After inappbrowser window appear, the status bar become hidden in android devices, and the window opened in full screen mode.

## Information

Please test inappbrowser in any android device, you will see that no statusbar after inappbrowser window is open.

### Command or Code

var ref = cordova.InAppBrowser.open('http://apache.org', '_blank', 'location=yes');

### Environment, Platform, Device

Android 9
Any Android Device.

### Version information

Cordova cli 9.0.0
Cordova inappbrowser master version or previous.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by AlexeyMelnik22** [comment] 2019-12-31 21:25
i have the same problem, and i can't find an answer((

**Comment by mosabab** [comment] 2020-01-01 18:12
> i have the same problem, and i can't find an answer((

Maybe inappbrowser plugin not configure to use statusbar for android devices until now, maybe someone look into this to add suitable codes to let statusbar appear for inappbrowser (for android devices).

**Comment by AlexeyMelnik22** [comment] 2020-01-01 18:17
I hope so, but I saw on YouTube that other people had a status bar, but this may be due to the framework’s ionic

**Comment by AlexeyMelnik22** [comment] 2020-01-01 18:17
> Maybe inappbrowser plugin not configure to use statusbar for android devices until now, maybe someone look into this to add suitable codes to let statusbar appear for inappbrowser (for android devices).

I hope so, but I saw on YouTube that other people had a status bar, but this may be due to the framework’s ionic

**Comment by mosabab** [comment] 2020-01-01 18:19
> > Maybe inappbrowser plugin not configure to use statusbar for android devices until now, maybe someone look into this to add suitable codes to let statusbar appear for inappbrowser (for android devices).
> 
> I hope so, but I saw on YouTube that other people had a status bar, but this may be due to the framework’s ionic

can you please put the link of youtube regarding this.

**Comment by AlexeyMelnik22** [comment] 2020-01-01 18:38
> can you please put the link of youtube regarding this.
https://www.youtube.com/watch?v=fGtUvm4pvlE
https://www.youtube.com/watch?v=5wQ7CgPxY-U&t=366s
https://www.youtube.com/watch?v=F-GlVrTaeH0&t=42s
https://www.youtube.com/watch?v=Z7KqlvQm3oU&t=227s

I saw another video where an example was shown with a real smartphone, and not with an emulator, but I cant find it.

**Comment by mosabab** [comment] 2020-01-01 18:44
> > can you please put the link of youtube regarding this.
> > https://www.youtube.com/watch?v=fGtUvm4pvlE
> > https://www.youtube.com/watch?v=5wQ7CgPxY-U&t=366s
> > https://www.youtube.com/watch?v=F-GlVrTaeH0&t=42s
> > https://www.youtube.com/watch?v=Z7KqlvQm3oU&t=227s
> 
> I saw another video where an example was shown with a real smartphone, and not with an emulator, but I cant find it.

You need a real android device, not emulator.

The problem from plugin itself, not ionic or something else.

**Comment by AlexeyMelnik22** [comment] 2020-01-01 18:59
So I say, I saw a video with a real smartphone and the status bar was visible.

**Comment by AlexeyMelnik22** [comment] 2020-01-01 19:01
> You need a real android device, not emulator.
> 
> The problem from plugin itself, not ionic or something else.

So i say, i saw a video with a real smartphone, and the status bar was visible

**Comment by mosabab** [comment] 2020-01-06 17:11
@NiklasMerz  do you have any idea regarding this issue ?

**Comment by AlexeyMelnik22** [comment] 2020-01-06 17:16
> 
> 
> @NiklasMerz do you have any idea regarding this issue ?

Nope, i made my app without this((

**Comment by NiklasMerz** [comment] 2020-01-06 17:39
I never had any issues for my apps on Android. I am not sure what is expected behaviour. The IAB is fine as it is for me.

**Comment by mosabab** [comment] 2020-01-06 19:54
> I never had any issues for my apps on Android. I am not sure what is expected behaviour. The IAB is fine as it is for me.

Did you see statusbar active after inappbrowser window appear in your app ?

**Comment by NiklasMerz** [comment] 2020-01-07 07:35
Yes I see the statusbar on Android. A screenshot would probably help to understand this issue better.

**Comment by mosabab** [comment] 2020-01-07 11:48
@NiklasMerz 

Please look at the first picture, the main webview app here:

![1](https://user-images.githubusercontent.com/47486787/71893304-e8713000-3153-11ea-95a1-a5f2c71288b4.jpg)

if you open InAppBrowser, you will see that the status bar is hidden like this picture:

![2](https://user-images.githubusercontent.com/47486787/71893302-e8713000-3153-11ea-98d3-a8651a4a34e8.jpg)


- I am using the master version of cordova-plugin-inappbrowser
- I am using the master version of  cordova-plugin-statusbar
- I am using Cordova-android version 8.0.0 (Phonegap CLI 9.0.0).

Using this code to open inappbrowser:
`cordova.InAppBrowser.open('http://apache.org', '_blank', 'location=yes');`

**Comment by AlexeyMelnik22** [comment] 2020-01-07 11:57
So your status bar is visible!!! 
most likely, you just need to change the color!
try to add the string to config.xml, and u can try to change another color, and compile you app
![изображение](https://user-images.githubusercontent.com/54482003/71893772-33d80e00-3155-11ea-8aae-aa5704a7e603.png)

P.S  I don’t see the status bar at all.

**Comment by mosabab** [comment] 2020-01-07 11:59
> So your status bar is visible!!!
> most likely, you just need to change the color!
> try to add the string to config.xml, and u can try to change another color, and compile you app
> ![изображение](https://user-images.githubusercontent.com/54482003/71893772-33d80e00-3155-11ea-8aae-aa5704a7e603.png)
> 
> P.S I don’t see the status bar at all.

No, my friend, i am using lightcontent style in `config.xml` file, and also i set the statusbar background color to light colors. but the problem still appear.

**Comment by AlexeyMelnik22** [comment] 2020-01-07 12:16
> No, my friend, i am using lightcontent style in `config.xml` file, and also i set the statusbar background color to light colors. but the problem still appear.

However, you see the status bar.

**Comment by mosabab** [comment] 2020-01-07 12:23
> > No, my friend, i am using lightcontent style in `config.xml` file, and also i set the statusbar background color to light colors. but the problem still appear.
> 
> However, you see the status bar.

Yes, you see it in the main webview, but not seeing it after inappbrowser appear.

**Comment by mosabab** [comment] 2020-01-07 15:56
@NiklasMerz 

Please look at the first picture, the main webview app here:

![1](https://user-images.githubusercontent.com/47486787/71893304-e8713000-3153-11ea-95a1-a5f2c71288b4.jpg)

if you open InAppBrowser, you will see that the status bar is hidden like this picture:

![2](https://user-images.githubusercontent.com/47486787/71893302-e8713000-3153-11ea-98d3-a8651a4a34e8.jpg)


- I am using the master version of cordova-plugin-inappbrowser
- I am using the master version of  cordova-plugin-statusbar
- I am using Cordova-android version 8.0.0 (Phonegap CLI 9.0.0).

Using this code to open inappbrowser:
`cordova.InAppBrowser.open('http://apache.org', '_blank', 'location=yes');`

And leaving `config.xml` preferences to default values regarding cordova-plugin-statusbar

And also try to set `StatusBarBackgroundColor` to dark values or light values with same issue.

**Comment by NiklasMerz** [comment] 2020-01-07 17:16
In my example the inappbrowser does not have a location bar. Mabye that changes it. But the app I am developing with sets the status bar in Javascript, as well.

**Comment by mosabab** [comment] 2020-01-07 18:02
> In my example the inappbrowser does not have a location bar. Mabye that changes it. But the app I am developing with sets the status bar in Javascript, as well.

The status work work well and appear in the main webview app.

But: after i click to open inappbrowser window, the status bar become hidden, after I click on `Done` button, the status bar become active in the main webview again.

The problem from Cordova-Plugin-InAppbrowser.

This is my code:

`index.js` file:

`inAppBrowserRef = cordova.InAppBrowser.open('https://github.com/', '_blank', location=yes,hidden=yes,clearcache=yes,clearsessioncache=yes,closebuttoncolor=#ffffff,hideurlbar=yes,zoom=no");`

`config.xml` file:

`<plugin name="cordova-plugin-statusbar" spec="https://github.com/apache/cordova-plugin-statusbar.git#master" />`

**Comment by mosabab** [comment] 2020-01-07 19:25
@NiklasMerz 

Sorry for missed information.

I mean the statusbar become hidden meaning inappbrowser become in fullscreen

I need to set inappbrowser for android to let statusbar appear over inappbrowser.

**Comment by mosabab** [comment] 2020-01-07 20:06
@breautek 
Do you have any idea regarding this issue ?

**Comment by NiklasMerz** [comment] 2020-01-07 20:09
I just tried it in a demo app and I can reproduce this problem. It never really bothered me before.

**Comment by mosabab** [comment] 2020-01-07 20:13
> I just tried it in a demo app and I can reproduce this problem. It never really bothered me before.

Thanks for testing, so, what you think the problem was ?

**Comment by breautek** [comment] 2020-01-07 20:48
@mosabab  I have never used the in-app browser plugin in any of my apps, so I can't really provide much insight here, sorry.

Maybe android is behaving in a "fullscreen" layout mode? If so, the statusbar should appear you swipe down from the top of the screen.

**Comment by mosabab** [comment] 2020-01-08 17:55
> @mosabab I have never used the in-app browser plugin in any of my apps, so I can't really provide much insight here, sorry.
> 
> Maybe android is behaving in a "fullscreen" layout mode? If so, the statusbar should appear you swipe down from the top of the screen. If you do see that behaviour, I think the following line would be the cause of it.
> 
> https://github.com/apache/cordova-plugin-inappbrowser/blob/09ad59f7ef177007c5ed603147cff335d7cfaafa/src/android/InAppBrowser.java#L797

Thanks for your message,
Yes you are right
When I swipe from top of screen and i see the statusbar.

So how i can make it not full screen

**Comment by breautek** [comment] 2020-01-08 18:49
The statusbar show/hide API shows and hides the statusbar by putting android in fullscreen mode, or leaving fullscreen mode.

So the `show()` API uses the following code:

```java
// SYSTEM_UI_FLAG_FULLSCREEN is available since JellyBean, but we
// use KitKat here to be aligned with "Fullscreen"  preference
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
    int uiOptions = window.getDecorView().getSystemUiVisibility();
    uiOptions &= ~View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN;
    uiOptions &= ~View.SYSTEM_UI_FLAG_FULLSCREEN;


    window.getDecorView().setSystemUiVisibility(uiOptions);
}


// CB-11197 We still need to update LayoutParams to force status bar
// to be hidden when entering e.g. text fields
window.clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
```
https://github.com/apache/cordova-plugin-statusbar/blob/24d5f278d0b7ea77f2a966d803af79520f1bfc88/src/android/StatusBar.java#L95-L107

I'm not sure if it is as simple as replacing line 797 above with something similar to what I just posted, but worth a try. You could also try just simply commenting out that line. Maybe the in-app-browser should change the statusbar at all? If you want a statusbar change, then I think it makes more sense for the developer to use the statusbar plugin itself. Otherwise we are opening ourselves up to many potential conflicts.

**Comment by mosabab** [comment] 2020-01-08 18:50
> @mosabab I have never used the in-app browser plugin in any of my apps, so I can't really provide much insight here, sorry.
> 
> Maybe android is behaving in a "fullscreen" layout mode? If so, the statusbar should appear you swipe down from the top of the screen. If you do see that behaviour, I think the following line would be the cause of it.
> 
> https://github.com/apache/cordova-plugin-inappbrowser/blob/09ad59f7ef177007c5ed603147cff335d7cfaafa/src/android/InAppBrowser.java#L797

Thanks for the message, you are right.

If i swipe from the top i can see the statusbar for a while.

But how we can set an option for android to select full screen or not full screen

**Comment by breautek** [comment] 2020-01-08 19:03
I don't think any such configuration currently exists in inappbrowser, given that `InAppBrowser` appears to unconditionally sets `FLAG_FULLSCREEN`.

As a test, you can try to modify `InAppBrowser.java` and comment out line 797. You should be able to find the file in `<your-cordova-project>/platforms/android/app/src/main/org/apache/cordova/inappbrowser/InAppBrowser.java` (didn't double check the path, but should be something like that).

By commenting out line 797, (`dialog.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);`), in theory it should leave the statusbar as is?

Personally I'm not sure why `InAppBrowser` is making such an assumption about the statusbar.

**Comment by mosabab** [comment] 2020-01-08 19:07
> I don't think any such configuration currently exists in inappbrowser, given that `InAppBrowser` appears to unconditionally sets `FLAG_FULLSCREEN`.
> 
> As a test, you can try to modify `InAppBrowser.java` and comment out line 797. You should be able to find the file in `<your-cordova-project>/platforms/android/app/src/main/org/apache/cordova/inappbrowser/InAppBrowser.java` (didn't double check the path, but should be something like that).
> 
> By commenting out line 797, (`dialog.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);`), in theory it should leave the statusbar as is?
> 
> Personally I'm not sure why `InAppBrowser` is making such an assumption about the statusbar.

You are right.

Thanks for your message.

We hope who is familiar with android coding can modify this as an option to help users to decide what they can choose as preferred options.

Regards

**Comment by breautek** [comment] 2020-01-08 19:24
I think a bigger discussion will need to be made because if the in app browser touches the statusbar, then I would expect the statusbar to be reverted back to its original state when the brower is dismissed.

The inappbrowser could snapshot the current statusbar configuration to do that revert, but I assume the app could then change the statusbar while the inappbrowser is opened. If so, then there is an opening where the inappbrowser may conflict with what the developer wants.

Maybe I am misunderstanding something about the inappbrowser cause like I said, I never actually used this plugin before, but it seems to be it will be far more simpler if the inappbrowser simply didn't touch the statusbar at all and if the statusbar view should be changed, then the developer should use the `statusbar` plugin themselves to configure the statusbar exactly how they want.

@NiklasMerz You've been pretty active with the inappbrowser stuff, what do you think?

**Comment by NiklasMerz** [comment] 2020-01-08 19:39
I must admit I am not that familiar with Android development.

We recently discussed issues with the status bar on iOS (see #604 ). If we change iOS we should try to make Android work the same. I am not sure how Android should work and how much work it would be to implement a flag like you suggested.

For me personally the InAppBrowser works just fine Android, but I don't have requirements to show the statusbar.

**Comment by mosabab** [comment] 2020-01-08 21:33
> I must admit I am not that familiar with Android development.
> 
> We recently discussed issues with the status bar on iOS (see #604 ). If we change iOS we should try to make Android work the same. I am not sure how Android should work and how much work it would be to implement a flag like you suggested.
> 
> For me personally the InAppBrowser works just fine Android, but I don't have requirements to show the statusbar.

You are right,
But If inappbrowser with full screen in android not a problem for you doesn’t mean it also not a problem for others.

The right way to meet all user’s requirements to set fullscreen as an option for inappbrowser specially in this case (for android).

I think this an important point that must take into account for developers.

Regards

**Comment by NiklasMerz** [comment] 2020-01-08 21:56
We will keep an eye ob this issue and discuss options. There is room for improvements. 

Since you probably need a solution quicker, you could try to make changes yourself to solve that for you and share them as a pull request. @breautek already points to possible solutions above. Maybe you find something that moves this issue forward.

**Comment by mosabab** [comment] 2020-01-08 22:21
> We will keep an eye ob this issue and discuss options. There is room for improvements.
> 
> Since you probably need a solution quicker, you could try to make changes yourself to solve that for you and share them as a pull request. @breautek already points to possible solutions above. Maybe you find something that moves this issue forward.

Yes you are right,

I will try the method from @breautek and check if it solve this issue.

**Comment by mosabab** [comment] 2020-01-09 13:52
@breautek @NiklasMerz 

I found an old issue regarding this issue in this post:
https://github.com/apache/cordova-plugin-inappbrowser/issues/469

It seems same issue

**Comment by mosabab** [comment] 2020-01-09 14:25
@breautek @NiklasMerz 

I found an old issues regarding this issue in this post:
https://github.com/apache/cordova-plugin-inappbrowser/issues/469
https://github.com/apache/cordova-plugin-inappbrowser/issues/526

It seems same issue.

This issue appear since inappbrowser version 3.1.0.

This commit what change the behavior : https://github.com/apache/cordova-plugin-inappbrowser/commit/ec6af56fbd0e2d85f932914da576871da507b4c6

Thanks to @breautek about the note.

Removing this line ` dialog.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN); ` will fix the problem.

But the other problem appear which is : the statusbar background color not take the action, and appear in black background.

In my example here:

`function loadStopCallBack() {
if (cordova.platformId == "android") {

      StatusBar.overlaysWebView(false);
      StatusBar.backgroundColorByHexString("#0089d1");

    }`

So the : `StatusBar.backgroundColorByHexString("#0089d1");` not take the blue color, and still in black.

This not happen when fullscreen mode active.

**Comment by breautek** [comment] 2020-01-09 14:56
@Fiffi I know this is quite awhile ago, but do you remember the reasoning behind [ec6af56](https://github.com/apache/cordova-plugin-inappbrowser/commit/ec6af56fbd0e2d85f932914da576871da507b4c6)

I can't find any associated issue or PR for this commit.

**Comment by NiklasMerz** [comment] 2020-01-09 19:57
The PR is this one #262. It seems to be related with the leftoright issue (#610 ). The [issue is this one](https://issues.apache.org/jira/browse/CB-13969). I don't understand this change, yet:

**Comment by mosabab** [comment] 2020-01-09 20:02
> The PR is this one #262. It seems to be related with the leftoright issue (#610 ). The [issue is this one](https://issues.apache.org/jira/browse/CB-13969). I don't understand this change, yet:

Don’t make things conflict.

The PR for swapping lefttoright doesn’t related to this issue.

**Comment by NiklasMerz** [comment] 2020-01-09 20:06
> This commit that changed the behavior : [ec6af56](https://github.com/apache/cordova-plugin-inappbrowser/commit/ec6af56fbd0e2d85f932914da576871da507b4c6)

The commit you found was merged with #262 which added this lefttorigth option. So there is a connection. I don't understand what happens the but this PR and Jira issue might give you answers https://issues.apache.org/jira/browse/CB-13969

**Comment by breautek** [comment] 2020-01-09 21:07
Given the person who made the commit is different from the PR author, and the commit was seemingly added into the branch randomly, a commit that doesn't appear to be related to the issue the PR was resolving at all. I wonder if that rogue commit was accidental.

**Comment by jlomelino** [comment] 2020-02-11 00:22
> @breautek @NiklasMerz @mosabab 
>

I am actively trying to find a solution for this. I have rolled back InAppBrowser and StatusBar plugins several versions all the way back to a couple years ago and have followed all the suggestions here so far as well s the related issues. 

Older Android devices didn't bug me too much as full-screen apps. But now with newer Android devices (Samsung Note10+ for example) the big black status bar is really an issue. 

I'm actively engaged in this to try to pinpoint what is causing the issue and will post results back here if I unlock the issue. 

@mosabab  did you find a solution that works with the newer Android devices (Galaxy 10+, Note 10+, etc.)?

**Comment by mosabab** [comment] 2020-02-11 10:08
> > @breautek @NiklasMerz @mosabab
> 
> I am actively trying to find a solution for this. I have rolled back InAppBrowser and StatusBar plugins several versions all the way back to a couple years ago and have followed all the suggestions here so far as well s the related issues.
> 
> Older Android devices didn't bug me too much as full-screen apps. But now with newer Android devices (Samsung Note10+ for example) the big black status bar is really an issue.
> 
> I'm actively engaged in this to try to pinpoint what is causing the issue and will post results back here if I unlock the issue.
> 
> @mosabab did you find a solution that works with the newer Android devices (Galaxy 10+, Note 10+, etc.)?

Hi @jlomelino 

I am not familiar with android development.

But what i am doing it for temp solution is to change the black bar to your theme color, you can do it like this code in your javascript `index.js` for eg.:

` StatusBar.backgroundColorByHexString("#00ddff");`
You can replace `#00ddff` with your color theme.

In my example here I change the color after inappbrowser show like this:

`function loadStopCallBack() {

  if (inAppBrowserRef != undefined) {
   
      StatusBar.backgroundColorByHexString("#0089d1");

    inAppBrowserRef.show();

}

}`

This what i do for now, until any one can fix this issue.

Regards

**Comment by jlomelino** [comment] 2020-02-13 15:35
That definitely works as a quick workaround. Very nice!

My current lead is that a build of mine from October 2017 works perfectly without issues. I have taken all that code from the working build's inappbrowser and status bar java files and that should fix it but it does not so I am still digging. I do have a working model to compare and once I find what is different I will try to bridge it and will post my results.

I tried making all the changes in this thread to the inappbrowser and status bar java files and they don't seem to make any difference. I'll keep peeling back the layers of the onion :)

**Comment by PDLMobileApps** [comment] 2020-02-26 16:20
I just added a PR to fix this issue: https://github.com/apache/cordova-plugin-inappbrowser/pull/632

**Closed** 2020-03-24 13:24 UTC

**Comment by HanojHanu** [comment] 2020-06-19 11:06
iam still facing the issue my inAppBrowser  hide statusbar

cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"


Ionic CLI                     : 6.10.0 (C:\Users\HanojBudime\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.27
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 8 other plugins)

Utility:

   cordova-res : 0.14.0
   native-run  : 1.0.0

System:

   NodeJS : v12.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.1
   OS     : Windows 10

**Comment by mosabab** [comment] 2020-06-19 11:09
> iam still facing the issue my inAppBrowser hide statusbar
> 
> cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
> 
> Ionic CLI : 6.10.0 (C:\Users\HanojBudime\AppData\Roaming\npm\node_modules@ionic\cli)
> Ionic Framework : @ionic/angular 4.11.10
> @angular-devkit/build-angular : 0.803.27
> @angular-devkit/schematics : 8.1.3
> @angular/cli : 8.1.3
> @ionic/angular-toolkit : 2.2.0
> 
> Cordova:
> 
> Cordova CLI : 9.0.0 (cordova-lib@9.0.1)
> Cordova Platforms : android 8.1.0
> Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 8 other plugins)
> 
> Utility:
> 
> cordova-res : 0.14.0
> native-run : 1.0.0
> 
> System:
> 
> NodeJS : v12.13.0 (C:\Program Files\nodejs\node.exe)
> npm : 6.12.1
> OS : Windows 10

You should use the latest version of inappbrowser plugin which is v4.0.0

**Comment by matrixreal** [comment] 2020-12-14 16:29
same here
when i open a link using in app browser or when a dialogs pop up (after closing the dialogs) the statu bar disapear.

**Comment by aaayushsingh** [comment] 2021-02-27 22:32
For anyone still facing this, 

According to [Cordova plugin page](https://cordova.apache.org/docs/en/10.x/reference/cordova-plugin-inappbrowser/) 

> fullscreen: Sets whether the InappBrowser WebView is displayed fullscreen or not. In fullscreen mode, the status bar is hidden. Default value is **yes**.

so, in order to keep status bar visible, pass `fullscreen: "no"` in options

```
let browser = this.inAppBrowser.create(
      "https://github.com
      "_target",
      { zoom: "no", location: "no", fullscreen: "no" }
    );
```

**Comment by ibnsultan** [comment] 2022-07-19 11:29
> I don't think any such configuration currently exists in inappbrowser, given that `InAppBrowser` appears to unconditionally sets `FLAG_FULLSCREEN`.
> 
> As a test, you can try to modify `InAppBrowser.java` and comment out line 797. You should be able to find the file in `<your-cordova-project>/platforms/android/app/src/main/org/apache/cordova/inappbrowser/InAppBrowser.java` (didn't double check the path, but should be something like that).
> 
> By commenting out line 797, (`dialog.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);`), in theory it should leave the statusbar as is?
> 
> Personally I'm not sure why `InAppBrowser` is making such an assumption about the statusbar.

worked like a charm
