### ISSUE TITLE
iOS 11.4.1 XCode 10.0 after inAppBrowser closed, app does not respond to touch events

### ISSUE THREAD

**Issue by datamystic** [apache/cordova-plugin-inappbrowser#314] opened 2018-10-05 21:45 UTC
After the inAppBrowser is closed (after viewing a website), the app does not respond to normal touch events - touch, swipe etc. 

The app still handles timer events in the background, so potentially this is an issue with how events are intercepted between the inAppBrowser and the underlying app, but the interceptor is not removed correctly when the inAppBrowser is closed.

**Comment by PieterVanPoyer** [comment] 2018-10-08 16:45
Which version of the inappbrowser are you using? Which cordova version? Which cordova-ios version?

**Comment by datamystic** [comment] 2018-10-08 20:14
Which version of the inappbrowser are you using? 3.0.0
Which cordova version? 8.1.1
Which cordova-ios version? 4.5.5

**Comment by mobilestar2015** [comment] 2018-10-08 21:11
I also faced this issue when I am using forked version of this plugin.
I found the reason why the app is not responding to touch events.
In the latest code(master branch at the moment), it creates temp UIWindow for the inappbrowser controller but after it exits the controller, it doesn't remove newly created UIWindow from the superview.
So that there is UIWindow remained over the original UIWindow.
I resolved this issue by removing temp UIWindow on 'browerExit' method in CDVInAppBrowser.m
`if (tmpWindow != nil) {
        [tmpWindow removeFromSuperview];
        tmpWindow = nil;
  }`
Hope this helps you @datamystic

**Comment by moldstadt** [comment] 2018-10-09 06:16
Glad you found the solution @mobilestar2015.  Any chance of submitting a pull request so that we can get this issue resolved?

**Comment by PieterVanPoyer** [comment] 2018-10-09 06:31
Same case here. I used a fork of the plugin and the app suffered from the same behaviour.
But the datamystic uses the 3.0.0 version and not a fork of the 3.0.1-dev version.
Duplicate of https://github.com/apache/cordova-plugin-inappbrowser/issues/296 ?

**Comment by mobilestar2015** [comment] 2018-10-09 07:35
@moldstadt I created a PR for this bug fix.

**Comment by datamystic** [comment] 2018-10-09 10:53
> I also faced this issue when I am using forked version of this plugin.
> I found the reason why the app is not responding to touch events.
> In the latest code(master branch at the moment), it creates temp UIWindow for the inappbrowser controller but after the controller closed, it doesn't remove newly created UIWindow from the superview.
> So that there is UIWindow remained over the original UIWindow.
> I resolved this issue by removing temp UIWindow on 'browerExit' method in CDVInAppBrowser.m
> `if (tmpWindow != nil) { [tmpWindow removeFromSuperview]; tmpWindow = nil; }`
> Hope this helps you @datamystic

That issue matches my symptoms exactly. How do we get a PR done?

**Comment by jacobg** [comment] 2018-10-11 19:14
I'm having this problem on version 2.0.2, and I applied the following commit fix (not on npm yet) and it works fine:   https://github.com/apache/cordova-plugin-inappbrowser/pull/272/files

Does that fix not work for you?

**Comment by omniowner** [comment] 2018-10-14 03:32
#272 fixed my app having this same issue

**Comment by datamystic** [comment] 2018-10-15 20:57
> > I also faced this issue when I am using forked version of this plugin.
> > I found the reason why the app is not responding to touch events.
> > In the latest code(master branch at the moment), it creates temp UIWindow for the inappbrowser controller but after the controller closed, it doesn't remove newly created UIWindow from the superview.
> > So that there is UIWindow remained over the original UIWindow.
> > I resolved this issue by removing temp UIWindow on 'browerExit' method in CDVInAppBrowser.m
> > `if (tmpWindow != nil) { [tmpWindow removeFromSuperview]; tmpWindow = nil; }`
> > Hope this helps you @datamystic
> 
> That issue matches my symptoms exactly. How do we get a PR done?

I have tested this change and it works perfectly.

**Comment by gunchungpyo** [comment] 2018-10-20 04:50
Yes, I have same issue here is the detail
inAppBrowser 3.0.0
cordova-ios 4.5.4
cordova-cli 7.1.0

I tried to downgrade to inAppBrowser 1.7.4 the issue still there.
and finally solved it by downgrade to inAppBrowser 1.4.0

**Closed** 2018-10-29 21:01 UTC
