### ISSUE TITLE
Showing Black screen while opening the inappbrowser in ios device using xcode 11.4.1

### ISSUE THREAD

**Issue by kaleanil** [apache/cordova-plugin-inappbrowser#673] opened 2020-04-19 12:28 UTC
const browser = this.iab.create('https://ionicframework.com/docs','_blank');

![Capture](https://user-images.githubusercontent.com/31914792/79687769-3aebdd80-8267-11ea-90a0-6c6ee23bbe35.PNG)

**Comment by jcesarmobile** [comment] 2020-04-19 14:22
The template is there for a reason, please, don't delete it when creating issues.

Closing as I can't reproduce

**Closed by jcesarmobile** 2020-04-19 14:22 UTC
