### ISSUE TITLE
InAppBrowser: java.lang.IllegalArgumentException 

### ISSUE THREAD

**Issue by paamrutk** [apache/cordova-plugin-inappbrowser#470] opened 2019-05-02 07:38 UTC
Hello all,

We have found this error on Google Play Store console that seams to be an InAppBrowser problem

```
java.lang.IllegalArgumentException: 
  at android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:533)
  at android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:433)
  at android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:124)
  at android.app.Dialog.dismissDialog (Dialog.java:518)
  at android.app.Dialog.dismiss (Dialog.java:501)
  at org.apache.cordova.inappbrowser.InAppBrowser$5$1.onPageFinished (InAppBrowser.java:462)
  at vu.d (PG:307)
  at aCg.handleMessage (PG:72)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7032)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```

Please help on this I am getting this crash issue frequently.

**Comment by janpio** [comment] 2019-05-02 08:38
What version of the plugin?
What version of Cordova Android?

**Comment by paamrutk** [comment] 2019-05-02 12:32
Plugin Version:3.0.0
Cordova Android Version:7.1.4

**Comment by lknop** [comment] 2019-05-08 09:48
@janpio I have a bit more details. The issue also happens in cordova-android 8.0.0. We have an app with the inappbrowser plugin version built from master branch around February and it was not fixed by then. 

Judging from the statistics, the problem is prevalent in Samsung phones (~80% of cases) but also visible in Huawei and others. Regarding android version, we had single instances in android 6, and the newer the version the more frequent the problem. Currently 95% cases is android 9.

**Comment by janpio** [comment] 2019-05-08 10:09
Thanks @lknop, that is valuable information. (Btw. we will soon do a new minor/path release to get current `master` out)

Is this reproducible in any way? Best on an emulator?

**Comment by lknop** [comment] 2019-05-13 13:35
We are struggling to reproduce the issue, did not happen on any emulator, and we cannot cause the app to crash repeatably but sometimes we get a samsung phone to crash somehow. I'll report back if we have any success.

**Comment by timbru31** [comment] 2019-05-13 14:47
We are seeing the crash, too (only Samsung devices and Android 9). Unfortunately I have no reproducible example neither.

![image](https://user-images.githubusercontent.com/838003/57630951-da581900-759e-11e9-8977-f68cf4ea6cc4.png)

**Comment by EmeryGuillaume** [comment] 2019-05-20 13:33
Hello, we are also seeing this issue in our google play console (Cordova-android 8 / inappbrowser 3)
Attached is the devices and versions repartition.
I haven't found any way to reproduce the issue...
![screen playstore](https://user-images.githubusercontent.com/10091017/58025377-9b811080-7b14-11e9-8380-c1fe463a05e7.png)

**Comment by DooDiddle** [comment] 2019-05-21 18:00
Hello, I see the same issue:
Samsung Galaxy S9 (starqltesq), Android 9
java.lang.IllegalArgumentException: 
  at android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:533)
  at android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:433)
  at android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:124)
  at android.app.Dialog.dismissDialog (Dialog.java:518)
  at android.app.Dialog.dismiss (Dialog.java:501)
  at org.apache.cordova.inappbrowser.InAppBrowser$5$1.onPageFinished (InAppBrowser.java:462)
  at vl.d (PG:307)
  at aHZ.handleMessage (PG:72)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6981)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)

**Comment by ceyhunkeklik** [comment] 2019-07-04 05:58
Is this issue resolved on 3.1.0?

**Comment by janpio** [comment] 2019-07-04 07:54
I don't see a Pull Request referenced here that could have fixed this @ceyhunkeklik, so probably no (unless via unrelated changes).

Biggest problem is that until now there is no reproduction for this - so we don't understand why it is happening and how we could properly fix it.

**Comment by ceyhunkeklik** [comment] 2019-07-05 11:33
We've faced this issue on Android 8.1 and Android 9 devices. Our crash logs almost the same as the other ones.

`java.lang.IllegalArgumentException: 
  at android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:454)
  at android.view.WindowManagerGlobal.removeView (WindowManagerGlobal.java:380)
  at android.view.WindowManagerImpl.removeViewImmediate (WindowManagerImpl.java:140)
  at android.app.Dialog.dismissDialog (Dialog.java:687)
  at android.app.Dialog.dismiss (Dialog.java:670)
  at org.apache.cordova.inappbrowser.InAppBrowser$4$1.onPageFinished (Unknown Source)
  at ib.d (PG:323)
  at Ae.handleMessage (PG:72)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:7223)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)`

**Comment by syagawa** [comment] 2019-07-08 07:12
We are facing the same problem. In our app, the incidence rate is high in Samsung Galaxy S9, but it is also occurring in Sony Xperia XZ2 Compact.

**Comment by lethe2211** [comment] 2019-07-23 10:03
Hi, let me share our case...
I'm using inappbrowser 3.0.0 with Cordova 7.1.0 / cordova-android 6.4.0.

Here are the results on our Firebase Console.

> Fatal Exception: java.lang.IllegalArgumentException: View=DecorView@9fcd2f6[MainActivity] not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked + 485(WindowManagerGlobal.java:485)
       at android.view.WindowManagerGlobal.removeView + 394(WindowManagerGlobal.java:394)
       at android.view.WindowManagerImpl.removeViewImmediate + 126(WindowManagerImpl.java:126)
       at android.app.Dialog.dismissDialog + 375(Dialog.java:375)
       at android.app.Dialog.dismiss + 358(Dialog.java:358)
       at org.apache.cordova.inappbrowser.InAppBrowser$5$1.onPageFinished + 462(InAppBrowser.java:462)
       at uU.d + 307(PG:307)
       at aIV.handleMessage + 73(PG:73)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 338(Looper.java:338)
       at android.app.ActivityThread.main + 6764(ActivityThread.java:6764)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 858(ZygoteInit.java:858)

Almost all are from Android 9.

![image](https://user-images.githubusercontent.com/1718146/61702913-88402a80-ad7b-11e9-8a18-a9b07817e20e.png)

And several devices caused this issue.

![image](https://user-images.githubusercontent.com/1718146/61702970-a0b04500-ad7b-11e9-9245-0248a642a114.png)
![image](https://user-images.githubusercontent.com/1718146/61702988-a86fe980-ad7b-11e9-90af-d638c6ede645.png)
![image](https://user-images.githubusercontent.com/1718146/61703013-af96f780-ad7b-11e9-8b6f-73cff770d6e7.png)

Also, it happens after the app becomes foreground.

![image](https://user-images.githubusercontent.com/1718146/61703170-04d30900-ad7c-11e9-945f-a9aa958b1225.png)

Hope it helps.

**Comment by morou** [comment] 2019-07-27 08:35
Is this related to https://github.com/apache/cordova-plugin-inappbrowser/issues/348 ?

**Comment by uqbMtran** [comment] 2019-09-18 14:46
https://issues.apache.org/jira/browse/CB-13259

**Comment by springbov** [comment] 2019-11-12 19:28
We had this issue happen in our 'pre-launch report' before releasing on the play store.
I'm uploading the logcat file (with our product id replaced with com.companyname.product), and the test device info which it had failed on.

The log cat file is 35 megabytes un compressed, so I've zipped it to be more manageable.
[logcat_with_redactions.zip](https://github.com/apache/cordova-plugin-inappbrowser/files/3837811/logcat_with_redactions.zip)

![image](https://user-images.githubusercontent.com/17886873/68702871-c2aa1f00-0546-11ea-91ca-31ce24372b2d.png)
```
FATAL EXCEPTION: main
Process: com.companyname.product, PID: 17295
java.lang.IllegalArgumentException: View=DecorView@c24883a[MainActivity] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:485)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:394)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
	at android.app.Dialog.dismissDialog(Dialog.java:375)
	at android.app.Dialog.dismiss(Dialog.java:358)
	at org.apache.cordova.inappbrowser.InAppBrowser$6$1.onPageFinished(InAppBrowser.java:537)
	at sV.d(PG:311)
	at aHF.handleMessage(PG:73)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by JeetuChoudhary** [comment] 2019-11-20 08:42
We are also facing the same issue. And It is occurring around 90% in Samsung Devices on Android 9.
Our Project Info is Following:

**Ionic Framework Version: 3.20.0
Cordova version: 9.0.0 (cordova-lib@9.0.1)
cordova-android: 8.0.0
InAppBrowser: ^3.0.0**

Crash Showing in Firebase Crashlytics is the following:

```
Fatal Exception: java.lang.IllegalArgumentException: View=DecorView@ad05060[MainActivity] not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:533)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:433)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
       at android.app.Dialog.dismissDialog(Dialog.java:518)
       at android.app.Dialog.dismiss(Dialog.java:501)
       at org.apache.cordova.inappbrowser.InAppBrowser$6$1.onPageFinished(InAppBrowser.java:537)
       at pn.b(PG:2)
       at cC0.handleMessage(PG:64)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```
 
![image](https://user-images.githubusercontent.com/22294704/69222173-ec92bf80-0b9e-11ea-837c-ebbd8dc23c71.png)

You Might get Successful to reproduce it by doing the following:
**This is a crash caused by your app dismissing a dialog attached to an Activity that is finishing or finished. This can happen in a number of ways -- for example, if an AsyncTask is running while a ProgressDialog is showing, and the user rotates the device, causing the Activity to be recreated.**

**Comment by ricard-pons** [comment] 2019-11-27 09:42
Still having the same error log in the Play Console for Android 9 with 5.11.0 version of the plugin and Cordova 8.1.0.
Has anyone found a workaround to fix this?

**Comment by mjamal4u** [comment] 2019-12-10 20:17
From our stats we can see this issue is with most of the Samsung Devices only. I am pretty sure we don't code at Manufacture level.  For our App 95% of crashes is only for Samsung devices.

**Closed** 2020-03-20 14:07 UTC
Labels: bug, crash, has-pr, platform: android
