### ISSUE TITLE
Incompatibility with cordova-ios@6.0.0?

### ISSUE THREAD

**Issue by maxymczech** [apache/cordova-plugin-inappbrowser#716] opened 2020-06-05 10:43 UTC
# Bug Report

### What does actually happen?

I have updated my project to `cordova-ios@6.0.0`, trying to build the project and it fails on a `CompileC` command for `cordova-plugin-inappbrowser`

### Version information
`cordova-ios@6.0.0`
`cordova-plugin-inappbrowser@3.2.0`

## Checklist

- [ x ] I searched for existing GitHub issues
- [ x ] I updated all Cordova tooling to most recent version
- [ x ] I included all the necessary information above

**Comment by timbru31** [comment] 2020-06-05 11:00
Duplicate of #709

**Closed by timbru31** 2020-06-05 11:00 UTC
