### ISSUE TITLE
iOS AppFlow Build Errors

### ISSUE THREAD

**Issue by chukwumaokere** [apache/cordova-plugin-inappbrowser#596] opened 2019-12-22 11:10 UTC
# Bug Report

## Problem
When I try to build this app using Ionic's Appflow I get a long string of warnings and errors that cause my build to fail.

### What is expected to happen?
The build should suceed

### What does actually happen?
I get deprecation warnings and then reference to "self" errors. 

### Environment, Platform, Device

Appflow for iOS

### Version information

Cordova

Here are the errors: [appflowerrs.txt](https://github.com/apache/cordova-plugin-inappbrowser/files/3992377/appflowerrs.txt)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2019-12-22 16:19
Please list your cordova-ios version & plugin versions. You can find this information out by using the following commands:

`cordova platform ls`
`cordova plugin ls`

Thanks.

**Comment by chukwumaokere** [comment] 2019-12-22 18:24
> Please list your cordova-ios version & plugin versions. You can find this information out by using the following commands:
> 
> `cordova platform ls`
> `cordova plugin ls`
> 
> Thanks.

```
> cordova.cmd platform ls
Installed platforms:
  android 8.1.0
  ios 5.1.1
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0

> cordova.cmd plugin ls
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-email-composer 0.9.2 "EmailComposer"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic 5.4.5 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"

```

**Comment by breautek** [comment] 2019-12-22 18:27
Are you using the `WKWebViewOnly` preference?

**Comment by chukwumaokere** [comment] 2019-12-22 18:49
I.. don't know. Is there a place I can check for that?

> Are you using the `WKWebViewOnly` preference?

**Comment by breautek** [comment] 2019-12-22 18:56
There is a known issue with using `WKWebViewOnly` with the inappbrowser plugin reported at https://github.com/apache/cordova-plugin-inappbrowser/issues/583

This is because while cordova-ios hides the UIWebView APIs, inappbrowser still needs them and doesn't have the same flag.

You can try forking the plugin and applying the PR https://github.com/apache/cordova-plugin-inappbrowser/pull/584 to your own fork for a potential solution.

I'll be closing this issue as a duplicate of https://github.com/apache/cordova-plugin-inappbrowser/issues/583

If you have more valuable information, I would encourage you to participate in #583 in order to keeps things consolidated all in one place. Thanks.

**Closed by breautek** 2019-12-22 18:56 UTC
Labels: duplicate, platform: ios
