### ISSUE TITLE
Opening `comgooglemaps://` uri is opening another app. - iOS

### ISSUE THREAD

**Issue by Anuj-Raghuvanshi** [apache/cordova-plugin-inappbrowser#833] opened 2020-12-15 06:32 UTC
# Bug Report

## Problem

While opening google maps in iOS by using scheme `comgooglemaps://` , It is opening another app named [Pitch Gauge](https://apps.apple.com/us/app/pitch-gauge/id389715382) .

### What is expected to happen?

It should open Google Maps App.

### What does actually happen?

It redirects to Pitch Gauge App.

### Command or Code
1. Istall [Pitch Gauge](https://apps.apple.com/us/app/pitch-gauge/id389715382) app from App Store in iOS.
2. Put below code in your app and try to open - 
```
cordova.InAppBrowser.open( "comgooglemaps://?q=" + address, "_system");
```

### Environment, Platform, Device
- Platform - iOS.
- Device - iPhone XR (Can be reproduced in any iOS device.)

### Version information
Plugin version - 4.0.0
Cordova - 10.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by faugusztin** [comment] 2020-12-15 08:00
Unfortunately any application can declare any deep link prefix on iOS. For example this year i found a random app declaring cydia:// deep link prefix for their app. There is nothing an application initiating the deep link can do.

**Comment by Anuj-Raghuvanshi** [comment] 2020-12-15 08:44
Umm... But @faugusztin, I was just going through some random checks that if any other app is also facing the same problem. I checked whatsapp for this, But there it was working fine there. Have you any idea how they would be differentiating ?? How its working fine there?

**Comment by faugusztin** [comment] 2020-12-15 11:57
As the [Google Maps documentation](https://developers.google.com/maps/documentation/urls/ios-urlscheme) explains, the calling app got 2 choices:
- an app can call Google maps via[ universal links](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html), using 'standard' google maps URL. So if you try to open an URL of "https://www.google.com/maps/@42.585444,13.007813,6z", if Google Maps  is installed, it should catch that URL and open it in the app. By the definition of how universal links work (checked against an actual file on the webserver), these cannot be 'hijacked'. This is probably the way Whatsapp calls Google Maps.
- other option are the 'old' [URL schemes](https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app) of comgooglemaps://, comgooglemaps-x-callback:// and comgooglemapsurl://. These are not checked against any server side component, thus any app can declare these. That is why Apple recommends to use Universal links (literally the first bullet point of benefits is: "Unique. Unlike custom URL schemes, universal links can’t be claimed by other apps, because they use standard HTTP or HTTPS links to your website.").

**Comment by timbru31** [comment] 2020-12-15 13:11
I'm closing this issue since we won't add any exceptions or special handling for some sort of apps and Frantisek (thx!) explained why the issue is happening - nothing Apache Cordova can prevent.

**Closed by timbru31** 2020-12-15 13:11 UTC
