### ISSUE TITLE
event "message" not triggered on ios with version is '4.0.0'

### ISSUE THREAD

**Issue by AlwaysLoveme** [apache/cordova-plugin-inappbrowser#777] opened 2020-09-09 11:06 UTC
# Bug Report
i posted a message from webpage on appbrower, but not triggered on app

### What is expected to happen?
can trigger event 'message'

### What does actually happen?
not triggered

### Command or Code

```
  const browser = this.iab.create('http://192.168.2.17:8080/', '_blank', {
                // location: 'yes',
                // fullscreen: 'no',
                hideurlbar: 'yes',
                toolbarcolor: '#F5F7FA',
                lefttoright: 'yes',
                hidenavigationbuttons: 'yes',
                toolbarposition: 'top',
                usewkwebview: 'yes',
                transitionstyle: 'crossdissolve',
            });
            browser.show();
            browser.on('message').subscribe((res) => {
                console.log(res);
                browser.close();
            });
```
```
window.webkit.messageHandlers.cordova_iab.postMessage('1231231');
```

### Environment, Platform, Device

IOS 11/13/14 beta

### Version information

```
Ionic:

   Ionic CLI                     : 6.11.8 (/Users/zhuxian/.nvm/versions/node/v12.18.3/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 16 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/zhuxian/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.18.3 (/Users/zhuxian/.nvm/versions/node/v12.18.3/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 11.7 Build version 11E801a

```

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by sardapv** [comment] 2020-09-09 15:29
Hello @AlwaysLoveme , Please go through documentation.
Post message needs a stringified object . That is because of WkWebView on iOS.

do something like this in your web code:

var data  = '12345';
var message = { message: data };
window.webkit.messageHandlers.cordova_iab.postMessage(JSON.stringify(message));

**Comment by AlwaysLoveme** [comment] 2020-09-10 05:32
> Hello @AlwaysLoveme , Please go through documentation.
> Post message needs a stringified object . That is because of WkWebView on iOS.
> 
> do something like this in your web code:
> 
> ```
> var data  = '12345';
> var message = { message: data };
> window.webkit.messageHandlers.cordova_iab.postMessage(JSON.stringify(message));
> ```
> 
> on native handler you can put alert and retrieve data it will be in data.message where data is your argument in callback

thanks, it is working

**Comment by sardapv** [comment] 2020-09-10 08:48
@AlwaysLoveme  great, you can close this issue then. Thanks

**Comment by breautek** [comment] 2020-09-10 13:42
Thanks @sardapv for responding to this issue.

It looks resolved as "not a bug", so I'll close it.

**Closed by breautek** 2020-09-10 13:42 UTC

**Comment by Read1337** [comment] 2021-01-31 20:34
I'm having this issue with Android. Everything works fine in IOS but on android the event "message" is never triggered.

**Comment by jampy** [comment] 2023-02-02 15:22
for clarification: `postMessage()` appears to expect a String that's valid JSON.

```javascript
// This will work:
webkit.messageHandlers.cordova_iab.postMessage(JSON.stringify({one:1,two:2})):

// This also works: 
webkit.messageHandlers.cordova_iab.postMessage('{"valid":"JSON"}');

// But this does NOT work: 
webkit.messageHandlers.cordova_iab.postMessage('bla');
```

The `message` handler received the parsed JSON object, not a string:

```javascript
iabRef.addEventListener('message', event => {
  console.log(event.data); // logs an object, not a string
});
```
