### ISSUE TITLE
Uncaught Error: Module cordova-plugin-inappbrowser.inappbrowser does not exist.

### ISSUE THREAD

**Issue by shahind** [apache/cordova-plugin-inappbrowser#953] opened 2022-06-20 15:52 UTC
# Bug Report
After removing the plugin it is still in the project's requirements

## Problem
I installed and removed the plugin using ``cordova plugin remove``. But it is still in project's requirements and I get ``Uncaught Error: Module cordova-plugin-inappbrowser.inappbrowser does not exist.`` error. 

using ``cordova clean`` does not helps.

### Environment, Platform, Device

Device: Windows 10. My platform is Electron.

### Version information

Cordova Packages:

    cli: 11.0.0
        common: 4.0.2
        create: 4.0.0
        lib: 11.0.0
            common: 4.0.2
            fetch: 3.0.1
            serve: 4.0.0

Project Installed Platforms:

    android: 6.4.0
    browser: 6.0.0
    electron: 3.0.0

Project Installed Plugins:

    cordova-plugin-file: 6.0.2
    cordova-plugin-ionic-webview: 5.0.0
    cordova-plugin-media: 5.0.4
    cordova-plugin-network-information: 3.0.0

Environment:

    OS: Microsoft Windows 10 Pro 10.0.19044 (19044) (Windows 10.0.19044) x64
    Node: v16.13.2
    npm: 8.7.0

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment] 2022-09-25 03:53
Latest version of the plugin requires cordova-android version >=9.0.0, but you are using 6.4.0.
So Cordova CLI is probably installing an older version where there is no electron support or not installing the plugin at all because of conflicts between platforms requirements.

it’s not a bug on the plugin, so I’m closing
you should update cordova-android to 11.0.0

**Closed by jcesarmobile** 2022-09-25 03:53 UTC

**Comment by shahind** [comment] 2022-09-25 10:19
removing and adding the platforms again fixes the problem, but I'm not sure if it is a problem related to cordova-android 6. @jcesarmobile please pay attention that I'm not trying to install the plugin, I have removed it but it still exists in the requirements. If the Cordova CLI had installed an older version or even not installed the plugin, it must disappear from the project's requirements after removing it. But I agree with you, it is not related to the plugin itself. It must be a problem with the Cordova CLI.

**Comment by breautek** [comment] 2022-09-25 14:56
Jcesar recommendation still applies. The CLI version and platform versions are fairly coupled. The interface between cordova-android 6 and cordova CLI is very likely incompatible as cordova-android 6 is pretty ancient and is not a supported version anymore.
