### ISSUE TITLE
Can not open camera when I click input type="file" on Android devices

### ISSUE THREAD

**Issue by jeffersonveloso** [apache/cordova-plugin-inappbrowser#477] opened 2019-05-09 14:05 UTC
# Bug Report

### What is expected to happen?

I can not open the option to use the camera in inappbrowser using the input file. I have already requested permissions with plugin diagnostic, I made direct changes in the java plugin indicated in issue https://github.com/apache/cordova-plugin-inappbrowser/issues/328, and nothing to appear the option to use the camera only opens the file explorer.

### What does actually happen?
Open the file explorer.

## Information
PLUGIN INAPPBROWSER VERSION 3.0.0

### Command or Code
Input file.

### Environment, Platform, Device
Android, all versions.

### Version information

Ionic:

   ionic (Ionic CLI)  : 4.10.1 (C:\Users\Jefferson\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : not available

System:

   Android SDK Tools : 26.1.1 (C:\Users\Jefferson\AppData\Local\Android\Sdk)
   NodeJS            : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment] 2019-05-09 14:13
Step 1: Do not delete the bug report issue template, but fill it: https://github.com/apache/cordova-plugin-inappbrowser/issues/new?template=BUG_REPORT.md

**Comment by jeffersonveloso** [comment] 2019-05-09 14:27
> Step 1: Do not delete the bug report issue template, but fill it: https://github.com/apache/cordova-plugin-inappbrowser/issues/new?template=BUG_REPORT.md

Update.

**Comment by janpio** [comment] 2019-05-09 14:31
> I can not open the option to use the camera in inappbrowser using the input file.

What code are you using?

What version of Cordova Android are you using?

> I have already requested permissions,

How?


> I made direct changes in the java plugin indicated in other issues

What exactly? What code? What issues?

**Comment by jeffersonveloso** [comment] 2019-05-09 14:46
> Qual versão do Cordova Android você está usando?
> Update tag in my post.
> > Não abra uma câmera de busca de câmera no inappbrowser usando o arquivo de entrada.
> 
> Qual código você está usando?
> With plugin Diagnostic.
> > Eu já solicitei Permissions
> 
> Como?
> 
> > Fiz mudanças diretas não plug-in java indicação em outros problemas
> 
> O que exatamente? Qual o código? Quais problemas?
https://github.com/apache/cordova-plugin-inappbrowser/issues/283

**Comment by jeffersonveloso** [comment] 2019-05-09 14:49
> Qual versão do Cordova Android você está usando?
> 
> > Não abra uma câmera de busca de câmera no inappbrowser usando o arquivo de entrada.
> 
> Qual código você está usando?
> 
> > Eu já solicitei Permissions
> 
> Como?
> 
> > Fiz mudanças diretas não plug-in java indicação em outros problemas
> 
> O que exatamente? Qual o código? Quais problemas?

Update

**Comment by janpio** [comment] 2019-05-09 14:58
> Cordova Platforms : android 7.1.4

Current version of Cordova Android is 8.x, you should try if updating this maybe already fixes the issue.

Your issue is also still missing the exact code you are using to do what you want to do.

**Comment by jeffersonveloso** [comment] 2019-05-09 18:13
> > Cordova Platforms : android 7.1.4
> 
> Current version of Cordova Android is 8.x, you should try if updating this maybe already fixes the issue.
> 
> Your issue is also still missing the exact code you are using to do what you want to do.
I've already upgraded my cord to version 9 and it still does not work. How I try to open the camera is simple. I open inappbrowser a page that has an input file, in the browser it opens the options to choose the file and in it appears the camera, using the plugin does not appear, it goes straight to the android file explorer and has no way to use the camera .

**Comment by janpio** [comment] 2019-05-09 18:29
And that is a feature that is usually possible when e.g. using the same page in another app using a webview like Facebook or Facebook Messenger?

**Comment by jeffersonveloso** [comment] 2019-05-09 18:34
> E isso é um recurso que geralmente é possível quando, por exemplo, usar a mesma página em outro aplicativo usando uma visualização da Web como o Facebook ou o Facebook Messenger?

Yes, in chrome, Facebook, Facebook Messenger.

**Comment by jeffersonveloso** [comment] 2019-05-27 13:14
Still no solution?

**Comment by jeffersonveloso** [comment] 2019-06-03 11:34
After inserting the modifications as indicated in issue #328  in the java InAppBrowser.java file in / plugins / cordova-plugin-inappbrowser / src / android I removed the folder platform and www and inserted again and the modifications appeared effect and appeared the camera.

Thanks!

**Comment by jcesarmobile** [comment] 2020-10-01 13:34
duplicate of https://github.com/apache/cordova-plugin-inappbrowser/issues/328

**Closed by jcesarmobile** 2020-10-01 13:34 UTC
Labels: platform: android, support
