### ISSUE TITLE
window.prompt as IPC unreliable as of ChromeWebView version 69

### ISSUE THREAD

**Issue by christianpanton** [apache/cordova-plugin-inappbrowser#299] opened 2018-09-17 16:33 UTC
Chrome recently introduced a limit to the length of data that can be passed through the `window.prompt` interface. It is now limited to [10240](https://chromium-review.googlesource.com/c/chromium/src/+/1112471/4/content/renderer/render_frame_impl.cc#2367) bytes.

This interface has been (mis-)used for [message passing](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/src/android/InAppBrowser.java#L247) in the Android implementation.

Unfortunately, this results in some quite unexpected behaviour, when Javascript evaluation results exceed 10240 bytes.

**Comment by jcesarmobile** [comment] 2018-12-02 19:59
Closing as duplicate of #303 as it has more information

**Closed by jcesarmobile** 2018-12-02 19:59 UTC
Labels: bug, platform: android
