### ISSUE TITLE
iOS App Crash when URL cannot be loaded

### ISSUE THREAD

**Issue by danielehrhardt** [apache/cordova-plugin-inappbrowser#944] opened 2022-04-29 11:11 UTC
# Bug Report

### What is expected to happen?
When a URL is not available (404, 500, DNS old) the InAppBrowser should show a error message. 

### What does actually happen?
The App Crash.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment] 2022-06-01 23:27
Can you provide a sample app that reproduces the issue?

**Comment by jcesarmobile** [comment] 2022-11-08 23:48
Closing since no sample app was provided

**Closed by jcesarmobile** 2022-11-08 23:48 UTC
Labels: info-needed
