### ISSUE TITLE
Installation of inappbrowser breaks cordova-plugin-googleplus

### ISSUE THREAD

**Issue by ausias-armesto** [apache/cordova-plugin-inappbrowser#674] opened 2020-04-20 00:07 UTC
# Bug Report

## Problem
I have found an incompatibility between the cordova-plugin-inappbrowser and cordova-plugin-googleplus as it was mentioned on https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/604.
If you have an app working with cordova-plugin-googleplus and then installs the cordova-plugin-inappbrowser, then Google login stops working

### What is expected to happen?
I expect that the Google popup consent screen appears having the cordova-plugin-inappbrowser installed.

### What does actually happen?

The Google login throws an error saying "popup_blocked_by_browser"

### Command or Code
I have created a git repo (https://github.com/ausias-armesto/googleplus-inapbrowser-incompatibility.git) where the problem can be reproduced. At the master branch there is a working use of the cordova-plugin-googleplus, while in the branch "incompatibility" I have executed the commands stated in the cordova-plugin-inappbrowser documentation:

```
ionic cordova plugin add cordova-plugin-inappbrowser
npm install @ionic-native/in-app-browser
```

Where the problem can be reproduced.I have used the following command to execute the project:
```
rm -rf platforms plugins node_modules package-lock.json && npm install && ionic cordova platform add browser && ionic cordova build browser && ionic cordova run browser --debug --source-map -l
```
### Solution
I have identified that if I remove the overwrite of the window.open from the plugin.xml it works again

```
    <!-- browser -->
    <platform name="browser">
        <js-module src="www/inappbrowser.js" name="inappbrowser">
            <clobbers target="cordova.InAppBrowser.open" />
            <!--<clobbers target="window.open" />-->
        </js-module>
        <js-module src="src/browser/InAppBrowserProxy.js" name="InAppBrowserProxy">
            <runs />
        </js-module>
    </platform>

```
¿ Does it make sense for this plugin to remove this clobbers?

### Environment, Platform, Device
I have used "cordova-plugin-inappbrowser": "^3.2.0", on a Browser platform

### Version information

```
Ionic:

   Ionic CLI                     : 5.2.3 (/Users/ausias/.nvm/versions/node/v13.6.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.0, (and 6 other plugins)

Utility:

   cordova-res : 0.8.1 (update available: 0.12.1)
   native-run  : 0.3.0 (update available: 1.0.0)

System:

   Android SDK Tools : 26.1.1 (/Users/ausias/Library/Android/sdk)
   NodeJS            : v13.6.0 (/Users/ausias/.nvm/versions/node/v13.6.0/bin/node)
   npm               : 6.13.4
   OS                : macOS High Sierra

```

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by timbru31** [comment] 2020-04-20 08:16
window.open is subject to be removed in #599

**Comment by timbru31** [comment] 2020-04-20 08:18
Actually, this is already merged. Can you try the mater of this plugin to see if the issue is fixed?

**Comment by ausias-armesto** [comment] 2020-04-20 09:04
If I use the master branch of the cordova-plugin-inappbrowser works fine now. I guess this issue can be closed

**Closed** 2020-04-20 09:04 UTC
